begin;
create extension if not exists pgtap with schema extensions;
select plan(49);

insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values
('00000000-0000-0000-0000-000000000000','16000000-0000-0000-0000-000000000001','authenticated','authenticated','ibet-owner@test.local','',now(),'{}','{}',now(),now()),
('00000000-0000-0000-0000-000000000000','16000000-0000-0000-0000-000000000002','authenticated','authenticated','ibet-other@test.local','',now(),'{}','{}',now(),now());
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select '00000000-0000-0000-0000-000000000000',('26000000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid,'authenticated','authenticated',null,'',now(),'{"provider":"anonymous","providers":["anonymous"]}','{}',now(),now() from generate_series(1,10)n;
insert into public.profiles(id) values('16000000-0000-0000-0000-000000000001'),('16000000-0000-0000-0000-000000000002');
insert into public.events(id,host_id,room_code,name,event_date,status,display_mode) values('af000000-0000-0000-0000-000000000001','16000000-0000-0000-0000-000000000001','IBET10','I Bet You Night','2026-08-20','lobby','game');
insert into public.teams(id,event_id,auth_user_id,name)
select ('df000000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid,'af000000-0000-0000-0000-000000000001',('26000000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid,'Team '||n from generate_series(1,10)n;

set local role authenticated;
select set_config('request.jwt.claims','{"sub":"16000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select lives_ok($$select public.setup_i_bet_you_round('af000000-0000-0000-0000-000000000001',3)$$,'Host sets up I Bet You');
select throws_ok($$select * from public.i_bet_you_group_members$$,'42501','permission denied for table i_bet_you_group_members','application role cannot directly read assignments');
reset role;
insert into public.event_rounds(id,event_id,position,game_type,title) values('bf000000-0000-0000-0000-000000000001','af000000-0000-0000-0000-000000000001',2,'guess_age','Guess the Age');
select is((select count(*) from public.i_bet_you_group_members),10::bigint,'every eligible Team is assigned');
select is((select count(distinct team_id) from public.i_bet_you_group_members),10::bigint,'each Team appears exactly once');
select ok((select max(n)-min(n)<=1 from(select count(*)n from public.i_bet_you_group_members group by group_id)x),'groups are balanced');
select is((select count(category_id) from public.i_bet_you_groups),(select count(distinct category_id) from public.i_bet_you_groups),'categories do not duplicate');
select set_config('test.group1',(select id::text from public.i_bet_you_groups order by position limit 1),true);
select set_config('test.group2',(select id::text from public.i_bet_you_groups order by position offset 1 limit 1),true);
select set_config('test.swap_a',(select team_id::text from public.i_bet_you_group_members where group_id=current_setting('test.group1')::uuid order by position limit 1),true);
select set_config('test.swap_b',(select team_id::text from public.i_bet_you_group_members where group_id=current_setting('test.group2')::uuid order by position limit 1),true);
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"16000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select lives_ok($$select public.swap_i_bet_you_teams('af000000-0000-0000-0000-000000000001',current_setting('test.swap_a')::uuid,current_setting('test.swap_b')::uuid)$$,'Host swaps Teams before play');
reset role;
select is((select group_id::text from public.i_bet_you_group_members where team_id=current_setting('test.swap_a')::uuid),current_setting('test.group2'),'swap persists authoritatively');
select set_config('test.bidder',(select team_id::text from public.i_bet_you_group_members where group_id=current_setting('test.group1')::uuid order by position limit 1),true);
select set_config('test.raiser',(select team_id::text from public.i_bet_you_group_members where group_id=current_setting('test.group1')::uuid order by position offset 1 limit 1),true);
select set_config('test.challenger',(select team_id::text from public.i_bet_you_group_members where group_id=current_setting('test.group1')::uuid order by position offset 2 limit 1),true);
select set_config('test.assignment',(select string_agg(group_id::text||team_id::text,',' order by team_id) from public.i_bet_you_group_members),true);
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"26000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":true}',true);
select throws_ok($$select public.setup_i_bet_you_round('af000000-0000-0000-0000-000000000001',3)$$,'42501','event owner required','Team cannot alter grouping');
select throws_ok($$select public.set_i_bet_you_bid(current_setting('test.group1')::uuid,current_setting('test.bidder')::uuid,7)$$,'42501','event owner required','Audience cannot mutate bids');
select ok(public.get_team_room_state('IBET10')->'i_bet_you' is not null,'Team hydration includes passive I Bet You state');

select set_config('request.jwt.claims','{"sub":"16000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select lives_ok($$select public.change_i_bet_you_category(current_setting('test.group1')::uuid)$$,'Host changes unstarted category');
reset role;
select ok((select category_id is not null from public.i_bet_you_groups where id=current_setting('test.group1')::uuid),'category persists');
select is((select string_agg(group_id::text||team_id::text,',' order by team_id) from public.i_bet_you_group_members),current_setting('test.assignment'),'group assignment persists unchanged');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"16000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select lives_ok($$select public.set_i_bet_you_bid(current_setting('test.group1')::uuid,current_setting('test.bidder')::uuid,7)$$,'Host records bid');
reset role;
select is((select current_bidder_team_id::text||':'||current_bid from public.i_bet_you_groups where id=current_setting('test.group1')::uuid),current_setting('test.bidder')||':7','opening I BET YOU persists bidder and bid');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"16000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select throws_ok($$select public.set_i_bet_you_bid(current_setting('test.group1')::uuid,current_setting('test.raiser')::uuid,7)$$,'new bid must be higher than current bid','equal bid is rejected');
select throws_ok($$select public.set_i_bet_you_bid(current_setting('test.group1')::uuid,current_setting('test.raiser')::uuid,6)$$,'new bid must be higher than current bid','lower bid is rejected');
select lives_ok($$select public.set_i_bet_you_bid(current_setting('test.group1')::uuid,current_setting('test.raiser')::uuid,9)$$,'second Team commits a raised I BET YOU bid');
reset role;
select is((select current_bidder_team_id::text||':'||current_bid from public.i_bet_you_groups where id=current_setting('test.group1')::uuid),current_setting('test.raiser')||':9','latest committed bidder and bid replace the prior committed bid');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"16000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select throws_ok($$select public.challenge_i_bet_you(current_setting('test.group1')::uuid,current_setting('test.raiser')::uuid)$$,'valid challenger required','latest bidder cannot challenge its own bid');
select throws_ok($$select public.setup_i_bet_you_round('af000000-0000-0000-0000-000000000001',3)$$,'grouping is locked after gameplay begins','grouping cannot regenerate after play begins');
select lives_ok($$select public.challenge_i_bet_you(current_setting('test.group1')::uuid,current_setting('test.challenger')::uuid)$$,'Host records Name Them');
reset role;
select is((select target_bid from public.i_bet_you_groups where id=current_setting('test.group1')::uuid),9,'challenge freezes the latest committed target');
select is((select challenged_bidder_team_id::text||':'||challenger_team_id::text from public.i_bet_you_groups where id=current_setting('test.group1')::uuid),current_setting('test.raiser')||':'||current_setting('test.challenger'),'challenge infers the latest bidder and selected challenger');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"16000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select lives_ok($$select public.correct_i_bet_you_showdown(current_setting('test.group1')::uuid,current_setting('test.bidder')::uuid,current_setting('test.challenger')::uuid,8)$$,'Host corrects showdown before timer');
select lives_ok($$select public.start_i_bet_you_timer(current_setting('test.group1')::uuid)$$,'Host starts timer');
reset role;
select is((select extract(epoch from(countdown_deadline_at-countdown_started_at))::integer from public.i_bet_you_groups where id=current_setting('test.group1')::uuid),60,'timer is server-authoritative 60 seconds');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"26000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":true}',true);
select throws_ok($$select public.start_i_bet_you_timer(current_setting('test.group1')::uuid)$$,'42501','event owner required','Team cannot start timer');
select set_config('request.jwt.claims','{"sub":"16000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select lives_ok($$select public.judge_i_bet_you_group(current_setting('test.group1')::uuid,true)$$,'SUCCESS is committed');
select lives_ok($$select public.judge_i_bet_you_group(current_setting('test.group1')::uuid,true)$$,'result retry is idempotent');
reset role;
select is((select count(*) from public.score_awards where metadata->>'i_bet_you_group_id'=current_setting('test.group1')),1::bigint,'SUCCESS awards exactly once');
select is((select team_id::text from public.score_awards where metadata->>'i_bet_you_group_id'=current_setting('test.group1')),current_setting('test.bidder'),'SUCCESS awards bidder');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"16000000-0000-0000-0000-000000000002","role":"authenticated","is_anonymous":false}',true);
select throws_ok($$select public.next_i_bet_you_group(current_setting('test.group1')::uuid)$$,'42501','event owner required','non-owner Host cannot control round');
select set_config('request.jwt.claims','{"sub":"16000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select lives_ok($$select public.next_i_bet_you_group(current_setting('test.group1')::uuid)$$,'next group remains Host-manual');
reset role;
select is((select state from public.i_bet_you_groups where id=current_setting('test.group1')::uuid),'complete','group completion persists');
select set_config('test.bidder2',(select team_id::text from public.i_bet_you_group_members where group_id=current_setting('test.group2')::uuid order by position limit 1),true);
select set_config('test.challenger2',(select team_id::text from public.i_bet_you_group_members where group_id=current_setting('test.group2')::uuid order by position offset 1 limit 1),true);
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"16000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select lives_ok($$select public.set_i_bet_you_bid(current_setting('test.group2')::uuid,current_setting('test.bidder2')::uuid,5)$$,'second group records bid');
select lives_ok($$select public.challenge_i_bet_you(current_setting('test.group2')::uuid,current_setting('test.challenger2')::uuid)$$,'second group challenge freezes');
select lives_ok($$select public.judge_i_bet_you_group(current_setting('test.group2')::uuid,false)$$,'FAIL may be judged before timer expiry');
reset role;
select is((select team_id::text from public.score_awards where metadata->>'i_bet_you_group_id'=current_setting('test.group2')),current_setting('test.challenger2'),'FAIL awards challenger');
select is((select count(*) from public.score_awards where metadata->>'game_type'='i_bet_you'),2::bigint,'one award exists per judged group');
select is((select state from public.i_bet_you_groups where id=current_setting('test.group2')::uuid),'result','result persists until manual next');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"16000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select ok(exists(select 1 from jsonb_array_elements(public.get_host_event_state('af000000-0000-0000-0000-000000000001')->'leaderboard')x where x->>'team_id'=current_setting('test.challenger2') and (x->>'points')::integer=5),'overall leaderboard includes I Bet You award');
select lives_ok($$select public.reset_i_bet_you_group(current_setting('test.group1')::uuid)$$,'Host resets only intended group');
reset role;
select is((select count(*) from public.score_awards where metadata->>'i_bet_you_group_id'=current_setting('test.group1')),0::bigint,'reset removes intended group award only');
select is((select state from public.i_bet_you_groups where id=current_setting('test.group1')::uuid),'waiting','reset restores group state');
select is((select count(*) from public.score_awards where metadata->>'i_bet_you_group_id'=current_setting('test.group2')),1::bigint,'reset preserves other group award');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"16000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select lives_ok($$select public.activate_hosted_round('af000000-0000-0000-0000-000000000001','bf000000-0000-0000-0000-000000000001')$$,'Host switches authoritatively to another hosted round');
reset role;
select is((select active_round_id from public.events where id='af000000-0000-0000-0000-000000000001'),'bf000000-0000-0000-0000-000000000001'::uuid,'event-level active round persists');

select * from finish();rollback;
