begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
values(md5('nc-host')::uuid,'authenticated','authenticated','nc-host@test.local','{}','{}',now(),now());
insert into public.profiles(id)values(md5('nc-host')::uuid);
insert into auth.users(id,aud,role,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select md5('nc-captain-'||n)::uuid,'authenticated','authenticated','{"provider":"anonymous","providers":["anonymous"]}'::jsonb,'{}',now(),now() from generate_series(1,10)n;
create function pg_temp.host()returns void language sql as $$select set_config('request.jwt.claims',jsonb_build_object('sub',md5('nc-host')::uuid,'role','authenticated','is_anonymous',false)::text,true)::text::void$$;
create function pg_temp.captain(n integer)returns void language sql as $$select set_config('request.jwt.claims',jsonb_build_object('sub',md5('nc-captain-'||n)::uuid,'role','authenticated','is_anonymous',true)::text,true)::text::void$$;
create function pg_temp.eid()returns uuid language sql as $$select current_setting('test.nc_event')::uuid$$;
create function pg_temp.pid()returns uuid language sql as $$select active_play_id from public.no_context_games where event_id=pg_temp.eid()$$;
create function pg_temp.team(n integer)returns uuid language sql as $$select id from public.teams where event_id=pg_temp.eid() and auth_user_id=md5('nc-captain-'||n)::uuid$$;
create function pg_temp.response(n integer)returns uuid language sql as $$select id from public.no_context_responses where play_id=pg_temp.pid()and team_id=pg_temp.team(n)$$;
create function pg_temp.act(a text)returns void language sql as $$select public.no_context_control(pg_temp.eid(),pg_temp.pid(),a)$$;
create function pg_temp.answer(n integer,body text)returns void language plpgsql as $$begin perform pg_temp.captain(n);perform public.submit_no_context_response(pg_temp.team(n),pg_temp.pid(),body);end$$;
create function pg_temp.vote(n integer,target integer,ballot integer default 0)returns void language plpgsql as $$begin perform pg_temp.captain(n);perform public.submit_no_context_vote(pg_temp.team(n),pg_temp.pid(),pg_temp.response(target),ballot);end$$;
create function pg_temp.stage()returns jsonb language sql as $$select private.no_context_state(pg_temp.eid())$$;
create function pg_temp.finish_round()returns void language plpgsql as $$begin perform pg_temp.host();perform pg_temp.act('reveal_3');perform pg_temp.act('reveal_2');perform pg_temp.act('reveal_1');end$$;
select pg_temp.host();
select set_config('test.nc_event',(public.create_event('No Context test','Venue','2026-09-24',10::smallint)).id::text,true);
select lives_ok($$select public.open_event_lobby(pg_temp.eid())$$,'new event opens normally');
update public.events set room_code='NC0001' where id=pg_temp.eid();
do $$declare n integer;mascots text[]:=array['frog','fox','bear','shark','octopus','dinosaur','ghost','robot','alien','rocket'];begin for n in 1..10 loop perform pg_temp.captain(n);perform public.join_event('NC0001','Table '||n,mascots[n]);end loop;end$$;
select pg_temp.host();
select lives_ok($$select public.setup_no_context(pg_temp.eid(),(select jsonb_agg(jsonb_build_object('instruction','Caption '||n,'media',jsonb_build_object('type','image','url','/no-context/meeting.svg')))from generate_series(1,5)n))$$,'Host prepares five prompts');
select is((select count(*)from public.no_context_prompts q join public.no_context_games g on g.round_id=q.round_id where g.event_id=pg_temp.eid()),5::bigint,'five persisted prompts');
select lives_ok($$select public.setup_no_context(pg_temp.eid(),'[]')$$,'setup retry does not reset game');
select ok(not has_table_privilege('authenticated','public.no_context_responses','select'),'raw responses inaccessible to host and team roles');
select ok(not has_table_privilege('authenticated','public.no_context_votes','select'),'raw votes inaccessible');
select ok(not has_function_privilege('authenticated','private.no_context_state(uuid,uuid)','execute'),'private shaping function not callable directly');
select lives_ok($$select pg_temp.act('start')$$,'Host starts No Context');
select is(pg_temp.stage()->'play'->>'phase','responses','response phase starts');
select is(pg_temp.stage()->>'team_count','10','participation frozen to ten Captains');
select ok((select deadline_at between clock_timestamp()+interval '43 seconds' and clock_timestamp()+interval '46 seconds' from public.no_context_plays where id=pg_temp.pid()),'45 second authoritative response deadline');
select is(public.get_host_event_state(pg_temp.eid())->'no_context'->'prompt',public.get_public_room_state('NC0001')->'no_context'->'prompt','Host and Audience receive same prompt/media');
select lives_ok($$select pg_temp.answer(1,'First draft')$$,'Captain submits');
select lives_ok($$select pg_temp.answer(1,'Final A')$$,'Captain can edit');
select is((select count(*)from public.no_context_responses where play_id=pg_temp.pid()),1::bigint,'one response per team');
select is((select body from public.no_context_responses where id=pg_temp.response(1)),'Final A','latest valid answer retained');
select throws_ok($$select pg_temp.answer(1,E' \n\t ')$$,'22023','response must be 1 to 140 characters','whitespace rejected');
select throws_ok($$select pg_temp.answer(1,repeat('x',141))$$,'22023','response must be 1 to 140 characters','overlength rejected');
select lives_ok($$select pg_temp.answer(2,repeat('x',140))$$,'140 characters accepted');
select pg_temp.answer(2,'Final B');select pg_temp.answer(3,'Final C');select pg_temp.answer(4,'Final D');
select is(pg_temp.stage()->'options','[]'::jsonb,'response contents hidden while writing');
select pg_temp.host();
select ok(not(public.get_host_event_state(pg_temp.eid())->'no_context')::text like '%Final A%','Host cannot see responses during writing');
select pg_temp.captain(1);
select is(public.get_team_room_state('NC0001')->'no_context'->'prompt',public.get_public_room_state('NC0001')->'no_context'->'prompt','Captain receives same prompt/media');
select is(public.get_team_room_state('NC0001')->'no_context'->>'my_response','Final A','Captain restores its saved response');
select throws_ok($$select public.submit_no_context_response(pg_temp.team(2),pg_temp.pid(),'Hijack')$$,'42501','Team ownership required','Captain cannot write for another team');
select throws_ok($$select pg_temp.act('close_responses')$$,'42501','event owner required','Captain cannot close submissions');
select pg_temp.host();select lives_ok($$select pg_temp.act('close_responses')$$,'Host closes with missing submissions');
select is(pg_temp.stage()->'play'->>'phase','reading','separate reading phase');
select is(jsonb_array_length(pg_temp.stage()->'options'),4,'only submitted responses are shown');
select ok(not(pg_temp.stage()->'options')::text ~ 'team_id|name|mascot|votes|placement|display_position','anonymous options contain no identity or totals');
select is((select count(distinct display_position)from public.no_context_responses where play_id=pg_temp.pid()),4::bigint,'shuffled display order persisted once');
select set_config('test.nc_order',(pg_temp.stage()->'options')::text,true);
select is((pg_temp.stage()->'options')::text,current_setting('test.nc_order'),'refresh preserves response order');
select throws_ok($$select pg_temp.answer(1,'Too late')$$,'P0001','responses are closed','cannot edit closed responses');
select pg_temp.host();select lives_ok($$select pg_temp.act('start_voting')$$,'Host opens voting after reading');
select ok((select deadline_at between clock_timestamp()+interval '28 seconds' and clock_timestamp()+interval '31 seconds' from public.no_context_plays where id=pg_temp.pid()),'30 second vote deadline');
select throws_ok($$select pg_temp.vote(1,1)$$,'42501','You cannot vote for your own response.','self vote rejected');
select lives_ok($$select pg_temp.vote(5,2)$$,'team without a response can vote');
select lives_ok($$select pg_temp.vote(5,1)$$,'vote can be changed');
select is((select count(*)from public.no_context_votes where play_id=pg_temp.pid()and team_id=pg_temp.team(5)),1::bigint,'one latest vote per team');
select pg_temp.vote(6,1);select pg_temp.vote(7,1);select pg_temp.vote(8,1);
select pg_temp.vote(1,2);select pg_temp.vote(9,2);select pg_temp.vote(2,3);select pg_temp.vote(10,3);select pg_temp.vote(3,4);
select is(pg_temp.stage()->>'vote_count','9','progress counts votes without targets');
select ok(not(pg_temp.stage()->'options')::text ~ 'votes|team_id|name|placement','no live vote totals or authors');
select pg_temp.host();select lives_ok($$select pg_temp.act('close_voting_0')$$,'Host closes original vote');
select is(pg_temp.stage()->'play'->>'phase','tiebreak','two-way podium tie enters tiebreak');
select is(pg_temp.stage()->'play'->>'ballot','2','only second/third unresolved');
select is(jsonb_array_length(pg_temp.stage()->'options'),2,'only tied responses included');
select is((select placement from public.no_context_responses where id=pg_temp.response(1)),1,'clear first place fixed');
select ok((select deadline_at between clock_timestamp()+interval '13 seconds' and clock_timestamp()+interval '16 seconds' from public.no_context_plays where id=pg_temp.pid()),'15 second tie deadline');
select lives_ok($$select pg_temp.act('close_voting_0')$$,'retry closing original vote is harmless');
select is(pg_temp.stage()->'play'->>'phase','tiebreak','retry does not close new tie ballot');
select throws_ok($$select pg_temp.vote(2,2,2)$$,'42501','You cannot vote for your own response.','self vote rejected during tie');
select throws_ok($$select pg_temp.vote(5,1,2)$$,'P0001','ineligible response','fixed first place excluded from tie');
select throws_ok($$select pg_temp.vote(5,2,0)$$,'P0001','voting is closed','late original ballot cannot become a tie vote');
select pg_temp.vote(2,3,2);select pg_temp.vote(3,2,2);
select pg_temp.host();select pg_temp.act('close_voting_2');
select is(pg_temp.stage()->'play'->>'phase','results','repeated tie locks results instead of looping');
select is(pg_temp.stage()->'play'->>'random_resolution','true','server persisted random fallback');
select is((select placement from public.no_context_responses where id=pg_temp.response(1)),1,'first place preserved through tiebreak');
select is((select count(distinct placement)from public.no_context_responses where play_id=pg_temp.pid()),3::bigint,'podium placements unique');
select is(pg_temp.stage()->'revealed','[]'::jsonb,'locked podium still hidden');
select is((select count(*)from public.score_awards where event_id=pg_temp.eid()),0::bigint,'ledger cannot spoil unrevealed winners');
select throws_ok($$select pg_temp.vote(5,2,2)$$,'P0001','voting is closed','locked votes cannot change');
select pg_temp.host();select throws_ok($$select pg_temp.act('reveal_1')$$,'P0001','reveal in podium order','cannot skip third/second reveal');
select pg_temp.act('reveal_3');
select is(jsonb_array_length(pg_temp.stage()->'revealed'),1,'only third revealed');
select is((select sum(points)from public.score_awards where event_id=pg_temp.eid()),1::bigint,'third earns one point');
select pg_temp.act('reveal_3');
select is((select count(*)from public.score_awards where event_id=pg_temp.eid()),1::bigint,'repeated reveal does not duplicate awards');
select pg_temp.act('reveal_2');select pg_temp.act('reveal_1');
select is((select sum(points)from public.score_awards where event_id=pg_temp.eid()),9::bigint,'podium awards total 5+3+1');
select is((select points from public.score_awards where event_id=pg_temp.eid()and team_id=pg_temp.team(1)),5,'four raw votes earn five points, not four');
select is(pg_temp.stage()->'revealed'->2->>'name','Table 1','first reveal includes correct author');
select is(pg_temp.stage()->'revealed'->2->>'votes','4','first reveal includes determining votes');
select pg_temp.captain(1);
select is(public.get_team_room_state('NC0001')->'no_context'->'revealed'->2->>'points','5','Captain gets placement feedback only after reveal');
select pg_temp.host();
select set_config('test.old_play',pg_temp.pid()::text,true);select pg_temp.act('next');
select is(pg_temp.stage()->'play'->>'number','2','next prompt selected');
select is(pg_temp.stage()->>'response_count','0','next round starts empty');
select is(pg_temp.stage()->>'vote_count','0','next round votes empty');
select is(pg_temp.stage()->'play'->>'ballot','0','next round has no tie');
select is(pg_temp.stage()->'revealed','[]'::jsonb,'next round reveal empty');
select is((select sum(points)from public.score_awards where event_id=pg_temp.eid()),9::bigint,'scores preserved between rounds');
select throws_ok($$select public.no_context_control(pg_temp.eid(),current_setting('test.old_play')::uuid,'next')$$,'P0001','stale round; refresh','retry Next cannot skip a prompt');
-- Round two: no responses; automatic response close and non-blocking empty result.
select pg_temp.act('start');update public.no_context_plays set deadline_at=clock_timestamp()-interval '1 second' where id=pg_temp.pid();
select throws_ok($$select pg_temp.answer(1,'Late')$$,'P0001','responses are closed','deadline rejects writes before Cron runs');
select lives_ok($$select private.process_no_context_transitions()$$,'server tick closes expired responses');
select is(pg_temp.stage()->'play'->>'phase','reading','automatic close reaches reading');
select pg_temp.host();select pg_temp.act('start_voting');
select is(pg_temp.stage()->'play'->>'phase','results','zero responses do not block');
select pg_temp.finish_round();select pg_temp.act('next');
-- Round three: one response, direct first place, no pointless ballot.
select pg_temp.act('start');select pg_temp.answer(1,'Only response');select pg_temp.host();select pg_temp.act('close_responses');select pg_temp.act('start_voting');
select is(pg_temp.stage()->'play'->>'phase','results','single response resolves without vote');
select pg_temp.finish_round();select pg_temp.act('next');
-- Round four: two responses and no votes, automatic vote close/random fallback.
select pg_temp.act('start');select pg_temp.answer(1,'One');select pg_temp.answer(2,'Two');select pg_temp.host();select pg_temp.act('close_responses');select pg_temp.act('start_voting');
update public.no_context_plays set deadline_at=clock_timestamp()-interval '1 second' where id=pg_temp.pid();
select throws_ok($$select pg_temp.vote(3,1)$$,'P0001','voting is closed','expired votes rejected before tick');
select lives_ok($$select private.process_no_context_transitions()$$,'server tick closes voting');
select is(pg_temp.stage()->'play'->>'phase','results','two responses/no votes resolve without deadlock');
select pg_temp.finish_round();select pg_temp.act('next');
-- Round five: multi-way tie, repeat tie handled by the autonomous tick.
select pg_temp.act('start');select pg_temp.answer(1,'One');select pg_temp.answer(2,'Two');select pg_temp.answer(3,'Three');select pg_temp.host();select pg_temp.act('close_responses');select pg_temp.act('start_voting');
select pg_temp.vote(4,1);select pg_temp.vote(5,2);select pg_temp.vote(6,3);select pg_temp.host();select pg_temp.act('close_voting_0');
select is(jsonb_array_length(pg_temp.stage()->'options'),3,'three-way tie includes all three responses');
select is(pg_temp.stage()->'play'->>'ballot','1','multi-way tie starts at first place');
update public.no_context_plays set deadline_at=clock_timestamp()-interval '1 second' where id=pg_temp.pid();
select private.process_no_context_transitions();
select is(pg_temp.stage()->'play'->>'phase','results','no tiebreak votes resolves server-side');
select pg_temp.finish_round();select pg_temp.act('finish');
select is(pg_temp.stage()->'play'->>'phase','complete','fifth round finishes the game');
select is((select display_mode from public.events where id=pg_temp.eid()),'leaderboard','overall leaderboard shown');
select ok(jsonb_array_length(public.get_public_room_state('NC0001')->'leaderboard')=10,'overall leaderboard retains all teams');
select ok((select sum(points)from public.score_awards where event_id=pg_temp.eid())>9,'cumulative ledger contains all played rounds');
select set_config('test.completed_play',pg_temp.pid()::text,true);select pg_temp.act('restart');
select is((select count(*)from public.score_awards where event_id=pg_temp.eid()and metadata->>'game_type'='no_context'),0::bigint,'restart removes No Context awards');
select is((select count(*)from public.no_context_responses r join public.no_context_plays p on p.id=r.play_id where p.event_id=pg_temp.eid()),0::bigint,'restart clears all responses and dependent votes');
select is(pg_temp.stage()->'play'->>'number','1','restart returns to first prompt');
select is(pg_temp.stage()->'play'->>'phase','ready','restart waits for Host');
select is((select count(*)from public.teams where event_id=pg_temp.eid()),10::bigint,'restart preserves Captains and teams');
select throws_ok($$select public.no_context_control(pg_temp.eid(),current_setting('test.completed_play')::uuid,'reveal_1')$$,'P0001','stale round; refresh','old reveal cannot score a restarted game');
-- Independent tie groups: do not rerun places already decided by the first tie.
select pg_temp.act('start');
select pg_temp.answer(1,'A');select pg_temp.answer(2,'B');select pg_temp.answer(3,'C');select pg_temp.answer(4,'D');
select pg_temp.host();select pg_temp.act('close_responses');select pg_temp.act('start_voting');
select pg_temp.vote(5,1);select pg_temp.vote(6,1);select pg_temp.vote(7,2);select pg_temp.vote(8,2);select pg_temp.vote(1,3);select pg_temp.vote(2,4);
select pg_temp.host();select pg_temp.act('close_voting_0');
select is(pg_temp.stage()->'play'->>'ballot','1','first independent tied group resolves first/second');
select pg_temp.vote(3,1,1);select pg_temp.vote(4,1,1);select pg_temp.vote(5,2,1);
select pg_temp.host();select pg_temp.act('close_voting_1');
select is(pg_temp.stage()->'play'->>'ballot','3','remaining group competes only for third');
select is((select placement from public.no_context_responses where id=pg_temp.response(1)),1,'tiebreak winner is fixed first');
select is((select placement from public.no_context_responses where id=pg_temp.response(2)),2,'tiebreak runner up is fixed second');
select pg_temp.vote(1,4,3);select pg_temp.host();select pg_temp.act('close_voting_3');
select is((select placement from public.no_context_responses where id=pg_temp.response(4)),3,'third-place tie winner takes only remaining podium slot');
select ok((select placement is null from public.no_context_responses where id=pg_temp.response(3)),'loser of third-place tie receives no placement');
select pg_temp.finish_round();
insert into public.score_awards(event_id,team_id,points,kind,reason,created_by)values(pg_temp.eid(),pg_temp.team(1),7,'manual_correction','Keep correction',md5('nc-host')::uuid);
select pg_temp.act('restart');
select is((select sum(points)from public.score_awards where event_id=pg_temp.eid()),7::bigint,'restart preserves manual corrections');
-- One participating Captain: no possible self-vote, but round still finishes.
update public.teams set status='removed' where event_id=pg_temp.eid()and id<>pg_temp.team(1);
select pg_temp.act('start');select pg_temp.answer(1,'Solo answer');select pg_temp.host();select pg_temp.act('close_responses');select pg_temp.act('start_voting');
select is(pg_temp.stage()->>'eligible_count','0','sole author has no eligible self-vote');
select is(pg_temp.stage()->'play'->>'phase','results','zero eligible voters cannot stall the round');
select pg_temp.finish_round();
select is((select sum(points)from public.score_awards where event_id=pg_temp.eid()),12::bigint,'sole response receives first place and preserves prior correction');
select * from finish();rollback;
