begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
values(md5('nc-host')::uuid,'authenticated','authenticated','nc-host@test.local','{}','{}',now(),now());
insert into public.profiles(id)values(md5('nc-host')::uuid);
insert into auth.users(id,aud,role,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select md5('nc-captain-'||n)::uuid,'authenticated','authenticated','{"provider":"anonymous","providers":["anonymous"]}'::jsonb,'{}',now(),now() from generate_series(1,10)n;
create function pg_temp.host()returns void language sql as $$select set_config('request.jwt.claims',jsonb_build_object('sub',md5('nc-host')::uuid,'role','authenticated','is_anonymous',false)::text,true)::text::void$$;
create function pg_temp.captain(n integer)returns void language sql as $$select set_config('request.jwt.claims',jsonb_build_object('sub',md5('nc-captain-'||n)::uuid,'role','authenticated','is_anonymous',true)::text,true)::text::void$$;
create function pg_temp.eid()returns uuid language sql as $$select current_setting('test.nc_event')::uuid$$;
create function pg_temp.pid()returns uuid language sql as $$select active_play_id from public.no_context_games where event_id=pg_temp.eid()$$;
create function pg_temp.team(n integer)returns uuid language sql as $$select id from public.teams where event_id=pg_temp.eid() and auth_user_id=md5('nc-captain-'||n)::uuid$$;
create function pg_temp.response(n integer)returns uuid language sql as $$select id from public.no_context_responses where play_id=pg_temp.pid()and team_id=pg_temp.team(n)$$;
create function pg_temp.act(a text)returns void language sql as $$select public.no_context_control(pg_temp.eid(),pg_temp.pid(),a)$$;
create function pg_temp.answer(n integer,body text)returns void language plpgsql as $$begin perform pg_temp.captain(n);perform public.submit_no_context_response(pg_temp.team(n),pg_temp.pid(),body);end$$;
create function pg_temp.vote(n integer,target integer,ballot integer default 0)returns void language plpgsql as $$begin perform pg_temp.captain(n);perform public.submit_no_context_vote(pg_temp.team(n),pg_temp.pid(),pg_temp.response(target),ballot);end$$;
create function pg_temp.stage()returns jsonb language sql as $$select private.no_context_state(pg_temp.eid())$$;
create function pg_temp.finish_round()returns void language plpgsql as $$begin perform pg_temp.host();perform pg_temp.act('reveal_3');perform pg_temp.act('reveal_2');perform pg_temp.act('reveal_1');end$$;
select pg_temp.host();
select set_config('test.nc_event',(public.create_event('No Context test','Venue','2026-09-24',10::smallint)).id::text,true);
select lives_ok($$select public.open_event_lobby(pg_temp.eid())$$,'new event opens normally');
update public.events set room_code='NC0001' where id=pg_temp.eid();
do $$declare n integer;mascots text[]:=array['frog','fox','bear','shark','octopus','dinosaur','ghost','robot','alien','rocket'];begin for n in 1..10 loop perform pg_temp.captain(n);perform public.join_event('NC0001','Table '||n,mascots[n]);end loop;end$$;
select pg_temp.host();
-- Prepare independent games, then exercise real scoring and accepted actions.
select public.save_guess_age_round(pg_temp.eid(),'A','[{"celebrity_name":"First","date_of_birth":"2000-01-01"},{"celebrity_name":"Second","date_of_birth":"2001-01-01"}]');
create function pg_temp.rid(kind text)returns uuid language sql as $$select id from public.event_rounds where event_id=pg_temp.eid()and game_type=kind$$;
create function pg_temp.q(n integer)returns uuid language sql as $$select id from public.questions where round_id=pg_temp.rid('guess_age')and position=n$$;
create function pg_temp.choose(kind text)returns void language sql as $$select public.select_hosted_game(pg_temp.eid(),pg_temp.rid(kind))::text::void$$;
create function pg_temp.resume(kind text)returns void language sql as $$select public.resume_hosted_game(pg_temp.eid(),pg_temp.rid(kind))::text::void$$;
select pg_temp.choose('guess_age');
select is((select active_question_id from public.events where id=pg_temp.eid()),pg_temp.q(1),'Start initializes a saved lineup');
select public.start_question(pg_temp.eid(),pg_temp.q(1),15);
select pg_temp.captain(1);select public.submit_guess(pg_temp.team(1),pg_temp.q(1),26);
select pg_temp.host();select public.lock_question(pg_temp.eid());select public.reveal_question(pg_temp.eid());
select ok((select sum(points)>0 from public.score_awards where event_id=pg_temp.eid()),'Game A awards points through its normal ledger');
select set_config('test.scores',(select jsonb_agg(to_jsonb(a)order by id)::text from public.score_awards a where event_id=pg_temp.eid()),true);
select public.advance_guess_age_question(pg_temp.eid());select public.start_question(pg_temp.eid(),pg_temp.q(2),15);
select pg_temp.captain(1);select public.submit_guess(pg_temp.team(1),pg_temp.q(2),25);select pg_temp.host();
select public.setup_no_context(pg_temp.eid(),(select jsonb_agg(jsonb_build_object('instruction','Caption '||n,'media',jsonb_build_object('type','image','url','/no-context/meeting.svg')))from generate_series(1,5)n));
update public.events set question_started_at=question_started_at-interval '6 seconds',question_deadline_at=question_deadline_at-interval '6 seconds',question_reveal_due_at=question_reveal_due_at-interval '6 seconds' where id=pg_temp.eid();
select pg_temp.choose('no_context');select pg_temp.act('start');
select is((select state from private.game_checkpoints where round_id=pg_temp.rid('guess_age')),'paused','A is paused when B starts');
select is((select count(*)from public.submissions where question_id=pg_temp.q(2)),1::bigint,'A accepted submission retained');
select is((select jsonb_agg(to_jsonb(a)order by id)::text from public.score_awards a where event_id=pg_temp.eid()),current_setting('test.scores'),'A ledger unchanged by switching');
select pg_temp.captain(2);select throws_ok($$select public.submit_guess(pg_temp.team(2),pg_temp.q(2),25)$$,'55000','game is paused; select it and resume before playing','stale A submission blocked');
select pg_temp.answer(1,'Saved caption A');select pg_temp.answer(2,'Saved caption B');select pg_temp.host();
update public.no_context_plays set deadline_at=clock_timestamp()+interval '8 seconds' where id=pg_temp.pid();
select pg_temp.choose('guess_age');
select is((select state from private.game_checkpoints where round_id=pg_temp.rid('no_context')),'paused','B becomes paused when selecting A');
select ok((public.get_public_room_state('NC0001')->>'game_paused')::boolean,'Audience sees selected game paused');
select ok((public.get_host_event_state(pg_temp.eid())->'game_pause'->>'selected_paused')::boolean,'Host reload sees selected game paused');
select is((select deadline_at from public.no_context_plays where id=pg_temp.pid()),null::timestamptz,'B response timer disabled');
select private.process_no_context_transitions(clock_timestamp()+interval '1 day');select private.process_guess_age_transitions(clock_timestamp()+interval '1 day');
select is(pg_temp.stage()->'play'->>'phase','responses','No Context does not advance invisibly');
select is((select status from public.events where id=pg_temp.eid()),'ready','Selecting A does not continue its timer');
select throws_ok($$select pg_temp.answer(1,'Changed while paused')$$,'55000','game is paused; select it and resume before playing','paused B rejects writes');select pg_temp.host();
select pg_temp.resume('guess_age');
select is((select active_question_id from public.events where id=pg_temp.eid()),pg_temp.q(2),'A restores question 2, not question 1');
select is((select status from public.events where id=pg_temp.eid()),'question','A restores active question phase');
select ok((select abs(extract(epoch from(e.question_deadline_at-clock_timestamp()))-extract(epoch from((c.event_state->>'question_deadline_at')::timestamptz-c.frozen_at)))<1 from public.events e join private.game_checkpoints c on c.round_id=e.active_round_id where e.id=pg_temp.eid()),'A retains only its remaining answer time');
select set_config('test.deadline',(select question_deadline_at::text from public.events where id=pg_temp.eid()),true);
select pg_temp.resume('guess_age');
select is((select question_deadline_at::text from public.events where id=pg_temp.eid()),current_setting('test.deadline'),'Resume retry cannot extend countdown');
select is((select jsonb_agg(to_jsonb(a)order by id)::text from public.score_awards a where event_id=pg_temp.eid()),current_setting('test.scores'),'Resume awards no duplicate points');
select is((select count(*)from private.game_checkpoints where event_id=pg_temp.eid()and state='running'),1::bigint,'Only selected A running');
-- Return to B: responses and voting share the same persisted play and ballot.
select pg_temp.choose('no_context');select pg_temp.resume('no_context');
select ok((select deadline_at between clock_timestamp()+interval '6 seconds' and clock_timestamp()+interval '9 seconds' from public.no_context_plays where id=pg_temp.pid()),'No Context resumes remaining time, not a new 45 second window');
select is((select count(*)from public.no_context_responses where play_id=pg_temp.pid()),2::bigint,'B retains response rows');
select pg_temp.act('close_responses');select pg_temp.act('start_voting');select pg_temp.vote(1,2);select pg_temp.host();
select set_config('test.votes',(select jsonb_agg(to_jsonb(v))::text from public.no_context_votes v where play_id=pg_temp.pid()),true);
select pg_temp.choose('guess_age');
select private.process_no_context_transitions(clock_timestamp()+interval '1 day');
select is(pg_temp.stage()->'play'->>'phase','voting','B voting stays frozen');
select pg_temp.choose('no_context');select pg_temp.resume('no_context');
select is((select jsonb_agg(to_jsonb(v))::text from public.no_context_votes v where play_id=pg_temp.pid()),current_setting('test.votes'),'Votes remain on same ballot after resume');
select pg_temp.vote(1,2);select pg_temp.host();
select is((select count(*)from public.no_context_votes where play_id=pg_temp.pid()),1::bigint,'Retry cannot create an additional vote');
select pg_temp.vote(2,1);select pg_temp.host();select pg_temp.act('close_voting_0');
select is(pg_temp.stage()->'play'->>'phase','tiebreak','Tied vote starts a timed tiebreak');
select set_config('test.tie',(pg_temp.stage()#-'{play,deadline_at}')::text,true);
select pg_temp.choose('guess_age');select private.process_no_context_transitions(clock_timestamp()+interval '1 day');
select pg_temp.choose('no_context');select pg_temp.resume('no_context');
select is((pg_temp.stage()#-'{play,deadline_at}')::text,current_setting('test.tie'),'Tiebreak round, ballot, placements and eligible options survive switching');
select pg_temp.act('close_voting_'||(pg_temp.stage()->'play'->>'ballot'));
select pg_temp.act('reveal_3');
select set_config('test.partial_reveal',pg_temp.stage()::text,true);
select pg_temp.choose('guess_age');select pg_temp.choose('no_context');select pg_temp.resume('no_context');
select is(pg_temp.stage()::text,current_setting('test.partial_reveal'),'Partial podium reveal resumes at the same place');
select pg_temp.finish_round();
select set_config('test.nc_scores',(select jsonb_agg(to_jsonb(a)order by id)::text from public.score_awards a where event_id=pg_temp.eid()),true);
select pg_temp.choose('guess_age');select pg_temp.choose('no_context');select pg_temp.resume('no_context');select pg_temp.act('reveal_1');
select is((select jsonb_agg(to_jsonb(a)order by id)::text from public.score_awards a where event_id=pg_temp.eid()),current_setting('test.nc_scores'),'Revisiting revealed No Context podium does not duplicate awards');
-- Table of Lies initial answer phase, responses, and reveal progress remain persisted.
select public.save_perfect_lie_round(pg_temp.eid(),'Table of Lies','[{"title":"General","questions":[{"question_text":"What is true?","correct_answer":"Truth"}]}]');
select set_config('test.plq',(select id::text from public.perfect_lie_questions where event_id=pg_temp.eid()limit 1),true);
select pg_temp.choose('perfect_lie');select public.advance_perfect_lie_question(pg_temp.eid(),current_setting('test.plq')::uuid);select public.start_perfect_lie_question(pg_temp.eid(),current_setting('test.plq')::uuid,20);
select pg_temp.captain(1);select public.submit_perfect_lie_answer(pg_temp.team(1),current_setting('test.plq')::uuid,'Truth');select pg_temp.host();
select set_config('test.pl_responses',(select jsonb_agg(to_jsonb(r))::text from public.perfect_lie_responses r where question_id=current_setting('test.plq')::uuid),true);
update public.perfect_lie_round_states set knowledge_deadline_at=clock_timestamp()+interval '7 seconds' where event_id=pg_temp.eid();
select pg_temp.choose('no_context');
select ok((select knowledge_deadline_at is null from public.perfect_lie_round_states where event_id=pg_temp.eid()),'Table of Lies timer disabled when off stage');
select pg_temp.choose('perfect_lie');
select pg_temp.captain(2);select throws_ok($$select public.submit_perfect_lie_answer(pg_temp.team(2),current_setting('test.plq')::uuid,'Truth')$$,'55000','game is paused; select it and resume before playing','Table of Lies rejects submissions until explicit resume');select pg_temp.host();select pg_temp.resume('perfect_lie');
select is((select jsonb_agg(to_jsonb(r))::text from public.perfect_lie_responses r where question_id=current_setting('test.plq')::uuid),current_setting('test.pl_responses'),'Table of Lies keeps accepted responses');
select ok((select knowledge_deadline_at>clock_timestamp()and knowledge_deadline_at<clock_timestamp()+interval '8 seconds' from public.perfect_lie_round_states where event_id=pg_temp.eid()),'Table of Lies remaining clock restored');
select pg_temp.captain(1);select public.submit_perfect_lie_lie(pg_temp.team(1),current_setting('test.plq')::uuid,'Lie one');
select pg_temp.captain(2);select public.submit_perfect_lie_answer(pg_temp.team(2),current_setting('test.plq')::uuid,'False');select public.submit_perfect_lie_lie(pg_temp.team(2),current_setting('test.plq')::uuid,'Lie two');select pg_temp.host();
select public.close_perfect_lie_writing(pg_temp.eid());
select pg_temp.captain(1);select public.submit_perfect_lie_vote(pg_temp.team(1),current_setting('test.plq')::uuid,(select id from public.perfect_lie_vote_options where question_id=current_setting('test.plq')::uuid and is_truth));select pg_temp.host();
select set_config('test.plvotes',(select jsonb_agg(to_jsonb(v))::text from public.perfect_lie_votes v where question_id=current_setting('test.plq')::uuid),true);
select pg_temp.choose('no_context');select pg_temp.choose('perfect_lie');select pg_temp.resume('perfect_lie');
select is((select jsonb_agg(to_jsonb(v))::text from public.perfect_lie_votes v where question_id=current_setting('test.plq')::uuid),current_setting('test.plvotes'),'Table of Lies voting resumes with accepted votes intact');
select pg_temp.captain(1);select throws_ok($$select public.submit_perfect_lie_answer(pg_temp.team(1),current_setting('test.plq')::uuid,'Different')$$,'55000',null,'Resuming does not reopen initial answer phase');select pg_temp.host();
select public.start_perfect_lie_reveal(pg_temp.eid());select public.advance_perfect_lie_reveal(pg_temp.eid());
select set_config('test.plreveal',(select jsonb_build_object('phase',phase,'reveal_index',reveal_index)::text from public.perfect_lie_round_states where event_id=pg_temp.eid()),true);
select set_config('test.plscores',(select jsonb_agg(to_jsonb(a)order by id)::text from public.score_awards a where event_id=pg_temp.eid()),true);
select pg_temp.choose('no_context');select pg_temp.choose('perfect_lie');select pg_temp.resume('perfect_lie');select public.start_perfect_lie_reveal(pg_temp.eid());
select is((select jsonb_build_object('phase',phase,'reveal_index',reveal_index)::text from public.perfect_lie_round_states where event_id=pg_temp.eid()),current_setting('test.plreveal'),'Table of Lies reveal position is not reset');
select is((select jsonb_agg(to_jsonb(a)order by id)::text from public.score_awards a where event_id=pg_temp.eid()),current_setting('test.plscores'),'Table of Lies scores cannot duplicate on resumed reveal');
-- I Bet You keeps groups, bids, challenger, and the countdown.
select public.setup_i_bet_you_round(pg_temp.eid());
select set_config('test.group',(select id::text from public.i_bet_you_groups where event_id=pg_temp.eid()order by position limit 1),true);
select set_config('test.bidder',(select team_id::text from public.i_bet_you_group_members where group_id=current_setting('test.group')::uuid order by position limit 1),true);
select set_config('test.challenger',(select team_id::text from public.i_bet_you_group_members where group_id=current_setting('test.group')::uuid order by position offset 1 limit 1),true);
select public.set_i_bet_you_bid(current_setting('test.group')::uuid,current_setting('test.bidder')::uuid,7);
select public.challenge_i_bet_you(current_setting('test.group')::uuid,current_setting('test.challenger')::uuid);
select public.start_i_bet_you_timer(current_setting('test.group')::uuid);
update public.i_bet_you_groups set countdown_deadline_at=clock_timestamp()+interval '12 seconds' where id=current_setting('test.group')::uuid;
select set_config('test.ibet',(select (to_jsonb(g)-'countdown_started_at'-'countdown_deadline_at'-'updated_at')::text from public.i_bet_you_groups g where id=current_setting('test.group')::uuid),true);
select pg_temp.choose('no_context');
select ok((select countdown_deadline_at is null from public.i_bet_you_groups where id=current_setting('test.group')::uuid),'I Bet You countdown freezes');
select pg_temp.choose('i_bet_you');select pg_temp.resume('i_bet_you');
select is((select (to_jsonb(g)-'countdown_started_at'-'countdown_deadline_at'-'updated_at')::text from public.i_bet_you_groups g where id=current_setting('test.group')::uuid),current_setting('test.ibet'),'I Bet You restores same showdown without resetting bids or groups');
select ok((select countdown_deadline_at between clock_timestamp()+interval '10 seconds' and clock_timestamp()+interval '13 seconds' from public.i_bet_you_groups where id=current_setting('test.group')::uuid),'I Bet You countdown resumes');
select is((select count(*)from private.game_checkpoints where event_id=pg_temp.eid()and state='running'),1::bigint,'Only one game running after switching among all four');
select public.judge_i_bet_you_group(current_setting('test.group')::uuid,true);
select set_config('test.ibetscores',(select jsonb_agg(to_jsonb(a)order by id)::text from public.score_awards a where event_id=pg_temp.eid()),true);
select pg_temp.choose('guess_age');select pg_temp.choose('i_bet_you');select pg_temp.resume('i_bet_you');select public.judge_i_bet_you_group(current_setting('test.group')::uuid,true);
select is((select jsonb_agg(to_jsonb(a)order by id)::text from public.score_awards a where event_id=pg_temp.eid()),current_setting('test.ibetscores'),'I Bet You judged result cannot duplicate on resume');
select pg_temp.choose('guess_age');select pg_temp.resume('guess_age');select public.lock_question(pg_temp.eid());select public.reveal_question(pg_temp.eid());select public.advance_guess_age_question(pg_temp.eid());select pg_temp.choose('guess_age');
select is((select status from public.events where id=pg_temp.eid()),'round_complete','Reselecting an already completed game never starts it again');
select pg_temp.choose('i_bet_you');
select is((select state from private.game_checkpoints where round_id=pg_temp.rid('guess_age')),'complete','A genuinely completed game stays complete when switched away');
select pg_temp.choose('no_context');select pg_temp.resume('no_context');select pg_temp.act('next');select pg_temp.act('start');
update public.no_context_plays set deadline_at=clock_timestamp()-interval '1 second' where id=pg_temp.pid();
select pg_temp.choose('i_bet_you');select pg_temp.choose('no_context');
select set_config('test.frozen',(select frozen_at::text from private.game_checkpoints where round_id=pg_temp.rid('no_context')),true);
select pg_temp.choose('i_bet_you');select pg_temp.choose('no_context');
select is((select frozen_at::text from private.game_checkpoints where round_id=pg_temp.rid('no_context')),current_setting('test.frozen'),'Selecting paused game again does not recapture or alter its remaining time');
select pg_temp.resume('no_context');
select ok((select deadline_at<=clock_timestamp()from public.no_context_plays where id=pg_temp.pid()),'Expired deadline stays expired when resumed');
select private.process_no_context_transitions();
select is(pg_temp.stage()->'play'->>'phase','reading','Expired phase advances normally only after resume');
select public.restart_guess_age_round(pg_temp.eid());
select is((select active_question_id from public.events where id=pg_temp.eid()),pg_temp.q(1),'Existing explicit restart clears completed checkpoint and selects first question');
select is((select status from public.events where id=pg_temp.eid()),'ready','Explicit restart is not overwritten by old completion checkpoint');
select ok(not has_function_privilege('authenticated','public.submit_guess_before_pause(uuid,uuid,integer)','execute'),'Clients cannot bypass pause guard');
select pg_temp.captain(1);select throws_ok($$select pg_temp.choose('guess_age')$$,'42501','event owner required','Only host can switch games');
select * from finish();rollback;
