begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
values(md5('defaults-host')::uuid,'authenticated','authenticated','defaults-host@test.local','{}','{}',now(),now());
insert into public.profiles(id)values(md5('defaults-host')::uuid);
insert into auth.users(id,aud,role,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select md5('defaults-captain-'||n)::uuid,'authenticated','authenticated','{"provider":"anonymous","providers":["anonymous"]}'::jsonb,'{}',now(),now() from generate_series(1,10)n;
create function pg_temp.host()returns void language sql as $$select set_config('request.jwt.claims',jsonb_build_object('sub',md5('defaults-host')::uuid,'role','authenticated','is_anonymous',false)::text,true)::text::void$$;
create function pg_temp.captain(n integer)returns void language sql as $$select set_config('request.jwt.claims',jsonb_build_object('sub',md5('defaults-captain-'||n)::uuid,'role','authenticated','is_anonymous',true)::text,true)::text::void$$;
create function pg_temp.eid()returns uuid language sql as $$select current_setting('test.nc_event')::uuid$$;
create function pg_temp.pid()returns uuid language sql as $$select active_play_id from public.no_context_games where event_id=pg_temp.eid()$$;
create function pg_temp.team(n integer)returns uuid language sql as $$select id from public.teams where event_id=pg_temp.eid() and auth_user_id=md5('defaults-captain-'||n)::uuid$$;
create function pg_temp.response(n integer)returns uuid language sql as $$select id from public.no_context_responses where play_id=pg_temp.pid()and team_id=pg_temp.team(n)$$;
create function pg_temp.act(a text)returns void language sql as $$select public.no_context_control(pg_temp.eid(),pg_temp.pid(),a)$$;
create function pg_temp.answer(n integer,body text)returns void language plpgsql as $$begin perform pg_temp.captain(n);perform public.submit_no_context_response(pg_temp.team(n),pg_temp.pid(),body);end$$;
create function pg_temp.vote(n integer,target integer,ballot integer default 0)returns void language plpgsql as $$begin perform pg_temp.captain(n);perform public.submit_no_context_vote(pg_temp.team(n),pg_temp.pid(),pg_temp.response(target),ballot);end$$;
create function pg_temp.stage()returns jsonb language sql as $$select private.no_context_state(pg_temp.eid())$$;
create function pg_temp.finish_round()returns void language plpgsql as $$begin perform pg_temp.host();perform pg_temp.act('reveal_3');perform pg_temp.act('reveal_2');perform pg_temp.act('reveal_1');end$$;
select pg_temp.host();
select set_config('test.nc_event',(public.create_event('No Context test','Venue','2026-09-24',10::smallint)).id::text,true);
select lives_ok($$select public.open_event_lobby(pg_temp.eid())$$,'new event opens normally');
update public.events set room_code='NC0001' where id=pg_temp.eid();
do $$declare n integer;mascots text[]:=array['frog','fox','bear','shark','octopus','dinosaur','ghost','robot','alien','rocket'];begin for n in 1..10 loop perform pg_temp.captain(n);perform public.join_event('NC0001','Table '||n,mascots[n]);end loop;end$$;
select pg_temp.host();
create function pg_temp.defaults() returns jsonb language sql as $$select public.get_host_event_state(pg_temp.eid())->'game_defaults'$$;
select is((select count(*)from jsonb_array_elements(pg_temp.defaults()->'i_bet_you'->'categories')c where (c->>'selected')::boolean),(select count(*)from public.i_bet_you_categories where active and host_id is null),'All built-in categories selected for a new host');
select ok(exists(select 1 from jsonb_array_elements(pg_temp.defaults()->'i_bet_you'->'categories')c where c->>'difficulty'='hard' and(c->>'selected')::boolean),'Initial selection includes hard categories, not only easy');
select set_config('test.films',(select id::text from public.i_bet_you_categories where title='Films' and host_id is null),true);
select set_config('test.comics',(select id::text from public.i_bet_you_categories where title='Comics' and host_id is null),true);
select lives_ok($$select public.save_i_bet_you_settings(pg_temp.eid(),array[current_setting('test.films')::uuid,current_setting('test.comics')::uuid],'[{"title":"Irish comedians","selected":true},{"title":"Local pubs","selected":false}]')$$,'Save selected built-ins and custom categories');
select is((select count(*)from private.i_bet_you_category_pool(pg_temp.eid())),3::bigint,'Pool contains only the two selected built-ins and selected custom');
select ok(exists(select 1 from jsonb_array_elements(pg_temp.defaults()->'i_bet_you'->'categories')c where c->>'title'='Local pubs' and not(c->>'selected')::boolean),'Deselected custom category is still remembered');
select is((select count(*)from public.i_bet_you_categories where host_id=md5('defaults-host')::uuid),2::bigint,'Custom categories belong to the host');
select lives_ok($$select public.save_i_bet_you_settings(pg_temp.eid(),array[current_setting('test.films')::uuid,current_setting('test.comics')::uuid],'[{"title":"  Irish   comedians  ","selected":true},{"title":"films","selected":true}]')$$,'Duplicate custom and built-in titles are reused');
select is((select count(*)from public.i_bet_you_categories where host_id=md5('defaults-host')::uuid),2::bigint,'Retry does not duplicate custom categories');
select set_config('test.custom',(select id::text from public.i_bet_you_categories where host_id=md5('defaults-host')::uuid and title='Irish comedians'),true);
select throws_ok($$select public.save_i_bet_you_settings(pg_temp.eid(),'{}','[]')$$,'22023','select at least one category','Empty pool rejected');
select throws_ok($$select public.save_i_bet_you_settings(pg_temp.eid(),'{}','[{"title":"x"}]')$$,'22023','categories need 2 to 120 characters','Invalid custom name rejected');
select is((select count(*)from private.i_bet_you_category_pool(pg_temp.eid())),3::bigint,'Failed saves leave previous pool intact');
select set_config('test.first_event',pg_temp.eid()::text,true);
select set_config('test.future',(public.create_event('Future night','','2026-10-01',10::smallint)).id::text,true);
select is((select array_agg(id order by id)from private.i_bet_you_category_pool(current_setting('test.future')::uuid)),(select array_agg(id order by id)from private.i_bet_you_category_pool(pg_temp.eid())),'New night inherits host selection');
select lives_ok($$select public.save_i_bet_you_settings(current_setting('test.future')::uuid,array[current_setting('test.films')::uuid],'[]')$$,'Future night can change defaults');
select is((select count(*)from private.i_bet_you_category_pool(pg_temp.eid())),3::bigint,'Earlier configured game keeps its pool when defaults change');
select set_config('test.latest',(public.create_event('Latest night','','2026-10-02',10::smallint)).id::text,true);
select is((select array_agg(id)from private.i_bet_you_category_pool(current_setting('test.latest')::uuid)),array[current_setting('test.films')::uuid],'Following night uses updated defaults');
select is((select count(*)from jsonb_array_elements(public.get_host_event_state(current_setting('test.latest')::uuid)->'game_defaults'->'i_bet_you'->'categories')c where(c->>'custom')::boolean),2::bigint,'Custom library remains available in future nights even if deselected');
-- Host-only data and mutation boundaries.
select pg_temp.captain(1);
select throws_ok($$select public.save_i_bet_you_settings(pg_temp.eid(),array[current_setting('test.films')::uuid],'[]')$$,'42501','event owner required','Captain cannot change host defaults');
select ok(not(public.get_public_room_state('NC0001') ? 'game_defaults'),'Audience cannot read host defaults');
select ok(not(public.get_team_room_state('NC0001') ? 'game_defaults'),'Team cannot read host defaults');
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)values(md5('defaults-other')::uuid,'authenticated','authenticated','other@test.local','{}','{}',now(),now());
insert into public.profiles(id)values(md5('defaults-other')::uuid);
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('defaults-other')::uuid,'role','authenticated','is_anonymous',false)::text,true);
select set_config('test.other',(public.create_event('Other host','','2026-10-01',10::smallint)).id::text,true);
select is((select count(*)from jsonb_array_elements(public.get_host_event_state(current_setting('test.other')::uuid)->'game_defaults'->'i_bet_you'->'categories')c where(c->>'custom')::boolean),0::bigint,'Other host cannot see private custom categories');
select throws_ok($$select public.save_i_bet_you_settings(current_setting('test.other')::uuid,array[current_setting('test.custom')::uuid],'[]')$$,'22023','invalid category selection','Other host cannot select a known private category ID');
select ok(not has_table_privilege('authenticated','private.host_game_preferences','select'),'Preferences inaccessible through raw table reads');
select pg_temp.host();
-- Assignments and rerolls must both use the saved pool, with no duplicates.
select public.setup_i_bet_you_round(pg_temp.eid());
select is((select count(*)from public.i_bet_you_groups where event_id=pg_temp.eid()),2::bigint,'Ten teams form two groups');
select ok(not exists(select 1 from public.i_bet_you_groups where event_id=pg_temp.eid()and category_id not in(select id from private.i_bet_you_category_pool(pg_temp.eid()))),'All assigned categories are selected');
select is((select count(distinct category_id)from public.i_bet_you_groups where event_id=pg_temp.eid()),2::bigint,'Groups use distinct categories');
select set_config('test.group',(select id::text from public.i_bet_you_groups where event_id=pg_temp.eid()order by position limit 1),true);
select set_config('test.before_category',(select category_id::text from public.i_bet_you_groups where id=current_setting('test.group')::uuid),true);
select lives_ok($$select public.change_i_bet_you_category(current_setting('test.group')::uuid)$$,'Reroll uses another selected category');
select isnt((select category_id::text from public.i_bet_you_groups where id=current_setting('test.group')::uuid),current_setting('test.before_category'),'Reroll changes the category');
select ok(not exists(select 1 from public.i_bet_you_groups where event_id=pg_temp.eid()and category_id not in(select id from private.i_bet_you_category_pool(pg_temp.eid()))),'Reroll cannot reintroduce a deselected category');
select throws_ok($$select public.save_i_bet_you_settings(pg_temp.eid(),array[current_setting('test.films')::uuid],'[]')$$,'55000','category settings are locked after the game is prepared','Prepared games cannot have their pool replaced');
-- Insufficient pool must fail atomically, without partially creating groups.
insert into public.teams(event_id,auth_user_id,name)select current_setting('test.future')::uuid,md5('defaults-captain-'||n)::uuid,'Future '||n from generate_series(1,10)n;
select throws_ok($$select public.setup_i_bet_you_round(current_setting('test.future')::uuid)$$,'P0001','Select at least one different category per group before starting I Bet You.','Too few selected categories produces actionable error');
select is((select count(*)from public.i_bet_you_groups where event_id=current_setting('test.future')::uuid),0::bigint,'Failed setup creates no partial groups');
-- Persist the validated Guess the Age lineup with order and dates.
select public.save_guess_age_round(current_setting('test.latest')::uuid,'Saved lineup','[{"celebrity_name":"First star","date_of_birth":"1980-01-02"},{"celebrity_name":"Second star","date_of_birth":"1990-03-04"}]');
select is(public.get_host_event_state(current_setting('test.future')::uuid)->'game_defaults'->'guess_age'->0->>'celebrity_name','First star','Saved celebrity defaults available to another night');
select is(public.get_host_event_state(current_setting('test.future')::uuid)->'game_defaults'->'guess_age'->1->>'date_of_birth','1990-03-04','Remembered lineup preserves dates and order');
select throws_ok($$select public.save_guess_age_round(current_setting('test.future')::uuid,'Invalid','[]')$$,'22023','Guess the Age requires between 1 and 50 questions','Invalid lineup does not replace defaults');
select is(jsonb_array_length(public.get_host_event_state(current_setting('test.future')::uuid)->'game_defaults'->'guess_age'),2,'Failed save preserves the last successful lineup');
select is((select count(*)from public.questions where event_id=current_setting('test.latest')::uuid),2::bigint,'Remembering defaults does not alter another game’s questions');
select set_config('request.jwt.claims',jsonb_build_object('sub',md5('defaults-other')::uuid,'role','authenticated','is_anonymous',false)::text,true);
select is(public.get_host_event_state(current_setting('test.other')::uuid)->'game_defaults'->'guess_age','null'::jsonb,'Another host has no access to saved celebrity lineup');
select * from finish();rollback;
