const STORE_KEY='gameNightAdminV3';
const CHANNEL_NAME='gameNightLiveV3';
const channel='BroadcastChannel' in window?new BroadcastChannel(CHANNEL_NAME):null;
let state=load(),ticker=null,guess=sessionStorage.getItem('gameNightGuess')||'';
let teamId=sessionStorage.getItem('gameNightTeamId')||'';
function load(){try{return JSON.parse(localStorage.getItem(STORE_KEY))}catch{return null}}
function esc(s=''){return String(s).replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function initials(name='?'){return name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function round(){return state?.rounds?.find(r=>r.id===state?.live?.activeRoundId)}
function celeb(){const r=round();return r?.settings?.celebrities?.[state?.live?.questionIndex||0]}
function team(){return state?.teams?.find(t=>String(t.id)===String(teamId))}
function left(){return state?.live?.deadline?Math.max(0,Math.ceil((state.live.deadline-Date.now())/1000)):0}
function currentKey(){return `${state?.live?.activeRoundId||'none'}:${state?.live?.questionIndex||0}`}
function mySubmission(){return teamId?state?.live?.submissions?.[teamId]:null}
function myAward(){return (state?.live?.lastAwarded||[]).find(a=>String(a.id)===String(teamId))}
function publish(){localStorage.setItem(STORE_KEY,JSON.stringify(state));channel?.postMessage({type:'state',state})}
function chooseTeam(id){teamId=String(id);sessionStorage.setItem('gameNightTeamId',teamId);render()}
function pressDigit(d){if(state?.live?.status!=='question'||left()<=0)return;let next=(String(guess)+String(d)).replace(/^0+(?=\d)/,'');if(next.length>3)return;const n=Number(next);if(n>120)return;guess=next;sessionStorage.setItem('gameNightGuess',guess);render()}
function backspaceGuess(){guess=String(guess).slice(0,-1);sessionStorage.setItem('gameNightGuess',guess);render()}
function clearGuess(){guess='';sessionStorage.removeItem('gameNightGuess');render()}
function lockIn(){if(state?.live?.status!=='question'||left()<=0||!team())return;state.live.submissions ||= {};if(state.live.submissions[teamId]!=null)return;const value=Number(guess);if(!Number.isInteger(value)||value<1||value>120)return;state.live.submissions[teamId]=value;publish();render()}
function renderJoin(root){root.innerHTML=`<div class="app"><div class="top"><div class="brand"><div class="mark">GN</div>Game Night</div><div class="room">ROOM ${esc(state?.event?.roomCode||'—')}</div></div><section class="card"><p class="eyebrow">LOCAL TEAM TEST</p><h1>Choose your team</h1><p class="muted">For this prototype each browser tab acts like one team's phone. Real QR joining comes when we connect the app to a backend.</p><div class="field"><label>Team</label><select id="teamSelect"><option value="">Select a team…</option>${(state?.teams||[]).map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></div><button id="joinBtn" class="btn primary full" disabled>Use this team</button></section></div>`;const sel=document.getElementById('teamSelect'),btn=document.getElementById('joinBtn');sel.onchange=()=>btn.disabled=!sel.value;btn.onclick=()=>chooseTeam(sel.value)}
function render(){const root=document.getElementById('teamApp');if(!state){root.innerHTML='<div class="app waiting"><section class="card"><h1>Open the Admin first</h1><p class="muted">This team view needs the local Game Night event state.</p></section></div>';return}if(!team()){sessionStorage.removeItem('gameNightTeamId');teamId='';renderJoin(root);return}
 const t=team(),status=state.live?.status||'idle',r=round(),c=celeb(),submitted=mySubmission();
 if(status==='leaderboard'){const sorted=[...(state.teams||[])].sort((a,b)=>(b.total||0)-(a.total||0));root.innerHTML=`<div class="app"><div class="top"><div class="brand"><div class="mark">GN</div>${esc(t.name)}</div><div class="room">ROOM ${esc(state.event.roomCode)}</div></div><section class="card"><p class="eyebrow">CURRENT STANDINGS</p><h1>Leaderboard</h1>${sorted.map((x,i)=>`<div class="leader"><span class="place">${i+1}</span><strong>${esc(x.name)}</strong><b>${x.total||0} pts</b></div>`).join('')}<button class="switch" id="switchTeam">Switch test team</button></section></div>`;document.getElementById('switchTeam').onclick=()=>chooseTeam('');return}
 if(!r||r.type!=='guessAge'||!c||['idle','ready','roundComplete'].includes(status)){root.innerHTML=`<div class="app"><div class="top"><div class="brand"><div class="mark">GN</div>${esc(t.name)}</div><div class="room">ROOM ${esc(state.event.roomCode)}</div></div><div class="waiting"><section class="card"><div class="status-orb">${status==='roundComplete'?'✓':'…'}</div><p class="eyebrow">${status==='roundComplete'?'ROUND COMPLETE':'GET READY'}</p><h1>${status==='roundComplete'?'Nice work.':'Eyes on the big screen.'}</h1><p class="muted">Your answer controls will appear here when the host starts the next Guess the Age question.</p><button class="switch" id="switchTeam">Switch test team</button></section></div></div>`;document.getElementById('switchTeam').onclick=()=>chooseTeam('');return}
 const locked=submitted!=null||status!=='question'||left()<=0;const award=myAward();
 root.innerHTML=`<div class="app"><div class="top"><div class="brand"><div class="mark">GN</div>${esc(t.name)}</div><div class="room">Q${(state.live.questionIndex||0)+1}</div></div><section class="card question ${locked?'locked':''}"><div class="qhead"><div><p class="eyebrow">${status==='reveal'?'ANSWER REVEALED':locked?'ANSWER LOCKED':'GUESS THE AGE'}</p><strong>${esc(c.name)}</strong></div><div class="timer">${status==='question'?left():'✓'}</div></div><div class="team-celeb">${c.image?`<div class="team-celeb-bg" style="background-image:url('${esc(c.image)}')"></div><img class="team-celeb-main" src="${esc(c.image)}" alt="${esc(c.name)}">`:`<span class="team-celeb-initials">${esc(initials(c.name))}</span>`}<div class="team-celeb-name">${esc(c.name)}</div></div>${status==='reveal'?`<h1>Your guess: ${submitted??'—'}</h1><div class="result"><div class="stat"><span>Points</span><strong>+${award?.points??0}</strong></div><div class="stat"><span>Difference</span><strong>${award?.diff??'—'}</strong></div></div><p class="muted">The correct answer is on the main screen.</p>`:`<h1>How old are they?</h1><div class="age keypad-display ${!guess&&submitted==null?'empty':''}">${submitted??(guess||'—')}</div><div class="keypad">${[1,2,3,4,5,6,7,8,9].map(n=>`<button class="key" data-digit="${n}" ${locked?'disabled':''}>${n}</button>`).join('')}<button class="key action" id="clearGuess" ${locked?'disabled':''}>C</button><button class="key" data-digit="0" ${locked?'disabled':''}>0</button><button class="key action" id="backspaceGuess" ${locked?'disabled':''}>⌫</button></div><button class="btn primary full lock-answer" id="lockBtn" ${locked||!guess?'disabled':''}>${submitted!=null?'Locked in ✓':status==='question'&&guess?'Lock in '+guess:status==='question'?'Enter an age':'Answers locked'}</button><p class="small">Enter an age from 1–120, then lock it in before the timer reaches zero.</p>`}</section></div>`;
 if(status!=='reveal'){document.querySelectorAll('[data-digit]').forEach(btn=>btn.onclick=()=>pressDigit(btn.dataset.digit));document.getElementById('clearGuess').onclick=clearGuess;document.getElementById('backspaceGuess').onclick=backspaceGuess;document.getElementById('lockBtn').onclick=lockIn}
}
function startTicker(){clearInterval(ticker);ticker=setInterval(()=>{if(state?.live?.status==='question')render()},200)}
channel?.addEventListener('message',e=>{if(e.data?.type==='state'){state=e.data.state;render();startTicker()}});
window.addEventListener('storage',e=>{if(e.key===STORE_KEY&&e.newValue){state=JSON.parse(e.newValue);render();startTicker()}});
render();startTicker();
