// @vitest-environment jsdom
import {readFileSync} from 'node:fs'
import {NO_CONTEXT_TEST_PROMPTS} from './no-context-content.js'
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
let handlers=[],storage,snapshot,actions
const flush=async()=>{for(let i=0;i<30;i++)await Promise.resolve()}
const emit=()=>{window.gameNightRemoteSession=structuredClone(snapshot);window.dispatchEvent(new CustomEvent('game-night-remote-state',{detail:window.gameNightRemoteSession}))}
const plan=games=>storage.set('gameNightPlan:e',JSON.stringify({games,progress:{},excluded:[]}))
const item=(type,id=type)=>({id,type,title:{noContext:'No Context',iBetYou:'I Bet You',guessAge:'Guess the Age',perfectLie:'Table of Lies'}[type],settings:{}})
const setupGuess=()=>{snapshot.rounds=[{id:'ga',game_type:'guess_age',title:'Guess the Age',questions:[{id:'q',position:1,celebrity_name:'Ada',date_of_birth:'1980-01-01'}]}];snapshot.event.active_round_id='ga'}
beforeEach(()=>{
 vi.resetModules();vi.useFakeTimers();storage=new Map()
 vi.stubGlobal('localStorage',{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)})
 document.body.innerHTML=new DOMParser().parseFromString(readFileSync('index.html','utf8'),'text/html').body.innerHTML
 vi.stubGlobal('BroadcastChannel',class{postMessage(){}});vi.stubGlobal('confirm',vi.fn(()=>true))
 const original=window.addEventListener.bind(window);vi.spyOn(window,'addEventListener').mockImplementation((type,handler,...rest)=>{handlers.push([type,handler]);original(type,handler,...rest)})
 snapshot={event:{id:'e',name:'Mic Check',room_code:'ABC123',event_date:'2026-09-25',status:'lobby',display_mode:'join'},rounds:[],teams:[{id:'a',name:'A',joined_at:new Date().toISOString()},{id:'b',name:'B',joined_at:new Date().toISOString()}],leaderboard:[],game_defaults:{i_bet_you:{saved_for_event:false,categories:[{id:'films',title:'Films',difficulty:'easy',selected:true},{id:'comics',title:'Comics',difficulty:'hard',selected:true}]}}}
 actions={saveIBetYouSettings:vi.fn(async categories=>{snapshot.game_defaults.i_bet_you={saved_for_event:true,categories:categories.map((c,i)=>({...c,id:c.id||`custom-${i}`}))};emit()}),setDisplay:vi.fn(async mode=>{snapshot.event.display_mode=mode;emit()}),refresh:vi.fn(async()=>emit()),saveGuessAgeRound:vi.fn(async()=>emit()),savePerfectLie:vi.fn(async()=>emit()),selectGame:vi.fn(async id=>{snapshot.event.active_round_id=id;snapshot.event.active_question_id='q';snapshot.event.status='ready';snapshot.event.display_mode='game';emit()}),advanceQuestion:vi.fn(async()=>{snapshot.event.status='round_complete';snapshot.event.active_question_id=null;emit()})}
 window.gameNightRemoteSession=snapshot;window.gameNightSupabaseActions=actions
})
afterEach(()=>{for(const [t,h]of handlers)window.removeEventListener(t,h);handlers=[];vi.clearAllTimers();vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals();delete window.gameNightRemoteSession;delete window.gameNightSupabaseActions})
describe('Unified Game Night Admin',()=>{
 it('starts empty with no phantom games and one primary destination',async()=>{await import('../admin.js');expect(document.querySelectorAll('.night-game')).toHaveLength(0);expect([...document.querySelectorAll('.nav-item')].map(x=>x.dataset.view)).toEqual(['night','teams','leaderboard']);expect(document.getElementById('nightStage').hidden).toBe(true)})
 it('reorders upcoming games and persists the running order',async()=>{plan([item('noContext'),item('iBetYou')]);await import('../admin.js');document.querySelector('.move-down').click();expect([...document.querySelectorAll('.night-game')].map(x=>x.dataset.game)).toEqual(['iBetYou','noContext']);expect(JSON.parse(storage.get('gameNightPlan:e')).games[0].type).toBe('iBetYou')})
 it('changes an upcoming game type and its settings without keeping a placeholder',async()=>{plan([item('noContext')]);await import('../admin.js');document.querySelector('.edit-round').click();const select=document.getElementById('settingsGameType');select.value='iBetYou';select.dispatchEvent(new Event('change'));expect(document.getElementById('drawerBody').textContent).toContain('grouped automatically');document.getElementById('doneRound').click();await flush();expect(document.querySelector('.night-game').dataset.game).toBe('iBetYou');expect(document.querySelectorAll('.night-game')).toHaveLength(1)})
 it('removes an upcoming game without deleting its server content or restoring it on refresh',async()=>{setupGuess();await import('../admin.js');document.querySelector('.edit-round').click();document.getElementById('deleteRound').click();emit();expect(document.querySelectorAll('.night-game')).toHaveLength(0);expect(snapshot.rounds).toHaveLength(1)})
 it('keeps settings drafts intact across server refresh and closes without changing saved values',async()=>{setupGuess();await import('../admin.js');document.querySelector('.edit-round').click();const input=document.getElementById('roundTitleInput');input.value='Draft title';input.dispatchEvent(new Event('input'));emit();expect(document.getElementById('roundTitleInput').value).toBe('Draft title');document.getElementById('closeDrawer').click();expect(document.querySelector('.night-game h3').textContent).toBe('Guess the Age')})
 it('saves Guess the Age through its existing service',async()=>{setupGuess();await import('../admin.js');document.querySelector('.edit-round').click();document.getElementById('doneRound').click();await flush();expect(actions.saveGuessAgeRound).toHaveBeenCalledWith('Guess the Age',expect.arrayContaining([expect.objectContaining({name:'Ada'})]));expect(document.getElementById('roundDrawer').classList.contains('open')).toBe(false)})
 it('moves directly into controls, locks editing, and returns to the next game on completion',async()=>{setupGuess();plan([item('guessAge'),item('noContext')]);await import('../admin.js');document.getElementById('startNextGame').click();await flush();expect(actions.selectGame).toHaveBeenCalledWith('ga');expect(document.getElementById('nightOverview').hidden).toBe(true);expect(document.getElementById('startQuestion')).not.toBeNull();document.querySelector('[data-night-order]').click();expect(document.querySelector('[data-game="guessAge"].night-game .edit-round')).toBeNull();snapshot.event.status='round_complete';snapshot.event.active_question_id=null;emit();await flush();expect(document.getElementById('nightStage').hidden).toBe(true);expect(document.getElementById('startNextGame').textContent).toContain('Next Game: No Context');expect(actions.setDisplay).toHaveBeenCalledWith('leaderboard')})
 it('keeps manual Audience mode available and avoids automatic standings after override',async()=>{setupGuess();snapshot.event.status='question';await import('../admin.js');document.querySelector('[data-display="join"]').click();await flush();actions.setDisplay.mockClear();snapshot.event.status='round_complete';snapshot.event.active_question_id=null;emit();await flush();expect(actions.setDisplay).not.toHaveBeenCalled();expect(JSON.parse(storage.get('gameNightPlan:e')).audienceManual).toBe(true)})
 it('does not overwrite live game state when saving a different Guess the Age lineup',async()=>{setupGuess();snapshot.no_context={round:{id:'nc',game_type:'no_context'},play:{id:'p',number:1,phase:'responses'},prompt:NO_CONTEXT_TEST_PROMPTS[0],options:[],revealed:[]};snapshot.event.active_round_id='nc';snapshot.event.status='question';await import('../admin.js');document.querySelector('[data-night-order]').click();document.querySelector('[data-game="guessAge"].night-game .edit-round').click();document.getElementById('doneRound').click();await flush();expect(actions.saveGuessAgeRound).not.toHaveBeenCalled();expect(document.getElementById('gameSettingsError').textContent).toContain('Finish the current game')})
 it('isolates plans and drafts when switching nights',async()=>{plan([item('noContext')]);await import('../admin.js');document.querySelector('.edit-round').click();snapshot={...snapshot,event:{...snapshot.event,id:'another',room_code:'DEF456'}};emit();expect(document.querySelectorAll('.night-game')).toHaveLength(0);expect(document.getElementById('roundDrawer').classList.contains('open')).toBe(false)})
})

describe('Switching from Tonight’s Games',()=>{
 it('offers Start beside Edit during live play, shows PAUSED, and requires a separate Resume',async()=>{
  setupGuess();snapshot.no_context={round:{id:'nc',game_type:'no_context'},play:{id:'p',number:1,phase:'responses'},prompt:NO_CONTEXT_TEST_PROMPTS[0],options:[],revealed:[]};snapshot.event.active_round_id='nc';snapshot.event.status='question';snapshot.event.display_mode='game';snapshot.game_pause={games:[]};
  actions.selectGame=vi.fn(async id=>{const previous=snapshot.event.active_round_id;snapshot.game_pause.games=snapshot.game_pause.games.filter(g=>g.round_id!==previous);snapshot.game_pause.games.push({round_id:previous,state:'paused'});snapshot.event.active_round_id=id;snapshot.event.active_question_id=id==='ga'?'q':null;snapshot.event.status='ready';emit()});
  actions.resumeGame=vi.fn(async id=>{snapshot.game_pause.games.find(g=>g.round_id===id).state='running';snapshot.event.status='question';emit()});
  await import('../admin.js');document.querySelector('[data-night-order]').click();
  const card=document.querySelector('[data-game="guessAge"].night-game');expect(card.querySelector('.edit-round')).not.toBeNull();card.querySelector('.start-game').click();await flush();
  expect(actions.selectGame).toHaveBeenCalledWith('ga');expect(document.getElementById('startQuestion')).not.toBeNull();document.querySelector('[data-night-order]').click();
  const paused=document.querySelector('[data-game="noContext"].night-game');expect(paused.textContent).toContain('PAUSED');expect(paused.querySelector('.edit-round')).toBeNull();paused.querySelector('.select-paused').click();await flush();
  expect(actions.resumeGame).not.toHaveBeenCalled();expect(document.getElementById('liveControl').textContent).toContain('The clock is stopped');expect(document.querySelector('[data-nc-action]')).toBeNull();
  document.getElementById('resumePausedGame').click();await flush();expect(actions.resumeGame).toHaveBeenCalledWith('nc');expect(document.getElementById('resumePausedGame')).toBeNull();expect(document.querySelector('[data-game="guessAge"].night-game').textContent).toContain('PAUSED');
 })
})

describe('Category and celebrity defaults in Game Settings',()=>{
 it('shows every category selected, supports custom categories, and saves deselections',async()=>{
  plan([item('iBetYou')]);await import('../admin.js');document.querySelector('.edit-round').click();expect(document.querySelectorAll('[data-category]:checked')).toHaveLength(2);
  const first=document.querySelector('[data-category="0"]');first.checked=false;first.dispatchEvent(new Event('change'));document.getElementById('customCategoryTitle').value='Irish comedians';document.getElementById('addIBetCategory').click();expect(document.querySelectorAll('[data-category]')).toHaveLength(3);
  emit();expect(document.querySelector('[data-category="0"]').checked).toBe(false);document.getElementById('doneRound').click();await flush();expect(actions.saveIBetYouSettings).toHaveBeenCalledWith(expect.arrayContaining([expect.objectContaining({id:'films',selected:false}),expect.objectContaining({title:'Irish comedians',selected:true})]));
  document.querySelector('.edit-round').click();expect(document.querySelector('[data-category="0"]').checked).toBe(false);expect(document.getElementById('drawerBody').textContent).toContain('Irish comedians');
 })
 it('keeps an empty selection unsaved and does not save cancelled edits',async()=>{
  plan([item('iBetYou')]);await import('../admin.js');document.querySelector('.edit-round').click();document.getElementById('clearCategories').click();document.getElementById('doneRound').click();await flush();expect(document.getElementById('gameSettingsError').textContent).toContain('Select at least one');expect(actions.saveIBetYouSettings).not.toHaveBeenCalled();document.getElementById('closeDrawer').click();document.querySelector('.edit-round').click();expect(document.querySelectorAll('[data-category]:checked')).toHaveLength(2)
 })
 it('starts a new Guess the Age lineup with ten editable celebrities',async()=>{
  await import('../admin.js');document.getElementById('addRound').click();document.querySelector('.game-option[data-game="guessAge"]').click();expect(document.querySelectorAll('.celeb-row')).toHaveLength(10);const name=document.querySelector('[data-field="name"]');name.value='My celebrity';name.dispatchEvent(new Event('input'));document.getElementById('addCeleb').click();expect(document.querySelectorAll('.celeb-row')).toHaveLength(11);expect(document.querySelector('[data-field="name"]').value).toBe('My celebrity');document.querySelector('.remove-celeb').click();expect(document.querySelectorAll('.celeb-row')).toHaveLength(10)
 })
 it('uses the account’s saved lineup when adding a game to a new night',async()=>{
  snapshot.game_defaults.guess_age=[{celebrity_id:'saved',celebrity_name:'Saved celebrity',date_of_birth:'1980-02-03'}];await import('../admin.js');document.getElementById('addRound').click();document.querySelector('.game-option[data-game="guessAge"]').click();expect(document.querySelectorAll('.celeb-row')).toHaveLength(1);expect(document.querySelector('[data-field="name"]').value).toBe('Saved celebrity');expect(document.querySelector('[data-field="dob"]').value).toBe('1980-02-03')
 })
})
