import { createGameNightClient, getSupabaseConfigError } from './supabase-client.js'
import { ensureAnonymousSession, normalizeRoom, ROOM_PATTERN } from './team-service.js'
import { containsSecretData, hydrateAudience, secondsRemaining } from './audience-service.js'
import QRCode from 'qrcode'
import { animateAge, buildAgeScale, differencePresentation, scatterGuessMarkers, suspenseSeconds, teamJoinUrl } from './audience-view.js'
import { iBetYouAudienceModel } from './i-bet-you.js'
import { mascotEmoji } from './mascots.js'

const root=document.getElementById('audienceApp'),room=normalizeRoom(new URLSearchParams(location.search).get('room')??''),supabase=createGameNightClient('game-night-audience-auth')
let state=null,channel=null,ticker=null,lastAnimatedQuestion=null
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))
function image(q){const url=q?.external_image_url||(q?.image_kind==='storage'?`${import.meta.env.VITE_SUPABASE_URL}/storage/v1/object/public/celebrity-images/${q.image_path}`:'');return url?`<div class="portrait-bg" style="background-image:url('${esc(url)}')"></div><img class="portrait-main" src="${esc(url)}" alt="${esc(q.celebrity_name)}">`:`<span>${esc((q?.celebrity_name||'?').split(' ').map(x=>x[0]).slice(0,2).join(''))}</span>`}
function guessCloud(){return `<div class="guess-cloud">${scatterGuessMarkers(state.guess_markers||[]).map(marker=>`<div class="guess-marker" style="--left:${marker.left}%;--top:${marker.top}%"><span>${mascotEmoji(marker.mascot_id)}</span><strong>${marker.guess}</strong></div>`).join('')}</div>`}
function revealStage(q){const scale=buildAgeScale(state.guess_markers||[],q.correct_age),scattered=scatterGuessMarkers(scale.markers);return `<section class="screen age-reveal-stage" id="ageRevealStage"><header><span>GUESS THE AGE · ${esc(q.celebrity_name)}</span><span>${state.guess_markers?.length||0} TEAM GUESSES</span></header><div class="age-scale-wrap"><div class="age-scale-range"><span>${scale.min}</span><span>${scale.max}</span></div><div class="age-scale"><div class="correct-age-marker" style="--position:${scale.answerPosition}%"><span>★</span><strong id="animatedAge">${lastAnimatedQuestion===q.id?q.correct_age:'–'.repeat(String(q.correct_age).length)}</strong><small>CORRECT AGE</small></div>${scale.markers.map((marker,index)=>{const difference=differencePresentation(marker.signed_difference),scatter=scattered[index],distance=Math.abs(scale.answerPosition-marker.position),direction=marker.position<=scale.answerPosition?'below':'above';return `<article class="scale-guess" style="--position:${marker.position}%;--lane:${marker.lane};--scatter-left:${scatter.left}%;--scatter-top:${scatter.top}%;--distance:${distance}" data-direction="${direction}"><div class="scale-pin">${mascotEmoji(marker.mascot_id)} <strong>${marker.guess}</strong></div><div class="distance-line"><span>${difference.short}</span></div><div class="final-team-result"><strong>${mascotEmoji(marker.mascot_id)} ${esc(marker.team_name)}</strong><span>GUESS ${marker.guess}</span><span>${difference.long}</span><b>+${marker.points}</b></div></article>`}).join('')}</div></div></section>`}
async function renderJoin(){const url=teamJoinUrl(location.origin,state.event.room_code);root.innerHTML=`<section class="holding join-screen"><div class="orb"></div><p>${esc(state.event.venue)}</p><h1>${esc(state.event.name)}</h1><h2>Join Game Night</h2><img id="joinQr" class="join-qr" alt="Scan to join room ${esc(state.event.room_code)}"><div class="join"><span>ROOM CODE</span><strong>${esc(state.event.room_code)}</strong></div><small>SCAN TO JOIN YOUR TEAM</small><div class="join-url">${esc(url)}</div></section>`;document.getElementById('joinQr').src=await QRCode.toDataURL(url,{width:420,margin:2,errorCorrectionLevel:'M',color:{dark:'#08090d',light:'#ffffff'}})}
function render(){clearInterval(ticker);if(!state)return;const e=state.event,q=state.question,r=state.round,left=secondsRemaining(state),expired=e.status==='question'&&left<=0;
  if(e.display_mode==='join'){renderJoin().catch(console.error);return}
  if(e.display_mode==='leaderboard'){root.innerHTML=`<section class="screen leaderboard"><header><span>${esc(e.venue)}</span><span>${esc(e.name)}</span></header><div class="board-wrap"><p class="kicker">CURRENT STANDINGS</p><h1>Leaderboard</h1><div class="board">${(state.leaderboard||[]).map((t,i)=>`<div class="board-row ${i<3?'top':''}"><span class="place">${i+1}</span><strong>${mascotEmoji(t.mascot_id)} ${esc(t.name)}</strong><span class="points">${t.points}<small> pts</small></span></div>`).join('')}</div></div></section>`;return}
  if(state.i_bet_you?.round?.id===e.active_round_id){renderIBetYou();return}
  if(!q||['lobby','ready','round_complete'].includes(e.status)){root.innerHTML=`<section class="holding"><div class="orb"></div><p>${esc(e.venue)}</p><h1>${esc(e.name)}</h1><small>${e.status==='round_complete'?'ROUND COMPLETE':'GET READY'}</small></section>`;return}
  if(e.status==='suspense'){const suspense=suspenseSeconds(state);root.innerHTML=`<section class="holding suspense"><p>ANSWERS LOCKED</p><h1>Reveal in <span id="suspenseCount">${suspense}</span></h1><small>${state.answer_count} / ${state.team_count} TEAMS LOCKED IN</small>${guessCloud()}</section>`;ticker=setInterval(()=>{const n=suspenseSeconds(state);const el=document.getElementById('suspenseCount');if(el)el.textContent=n;if(n<=0)hydrate().catch(console.error)},250);return}
  const reveal=e.status==='reveal',locked=e.status==='locked'||expired;if(reveal){root.innerHTML=revealStage(q);const stage=document.getElementById('ageRevealStage'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(lastAnimatedQuestion===q.id||reduced){lastAnimatedQuestion=q.id;stage.classList.add('organised','final');const target=document.getElementById('animatedAge');if(target)target.textContent=q.correct_age}else{lastAnimatedQuestion=q.id;requestAnimationFrame(()=>stage.classList.add('organised'));setTimeout(()=>animateAge({age:q.correct_age,target:document.getElementById('animatedAge'),reducedMotion:reduced}).then(()=>stage.classList.add('final')).catch(console.error),450)}return}root.innerHTML=`<section class="screen question-screen ${locked?'locked':'question'}"><header><span>ROUND ${r?.position||1} · ${esc(r?.title||'Guess the Age')}</span><span>QUESTION ${q.position} / ${r?.question_count||0}</span></header><div class="question-layout"><div class="portrait">${image(q)}</div><div class="copy"><p class="kicker">GUESS THE AGE</p><h1>${esc(q.celebrity_name)}</h1><p class="prompt">How old are they?</p><div class="answer-count">${state.answer_count} / ${state.team_count} Teams locked in</div></div><div class="countdown ${locked?'locked':''}">${e.status==='question'&&!expired?`<strong>${left}</strong><span>SECONDS</span>`:'<strong>✓</strong><span>ANSWERS LOCKED</span>'}</div></div>${guessCloud()}</section>`;
  if(e.status==='question'&&!expired)ticker=setInterval(()=>{const remaining=secondsRemaining(state);if(remaining<=0)render();else{const el=document.querySelector('.countdown strong');if(el)el.textContent=remaining}},250)
}
function renderIBetYou(){const model=iBetYouAudienceModel(state),game=state.i_bet_you,group=game.groups.find(g=>g.id===game.round.active_group_id),identity=id=>{const member=group?.members.find(x=>x.team_id===id);return `${mascotEmoji(member?.mascot_id)} ${esc(member?.name||'Team')}`};if(model.phase==='complete'||!group){root.innerHTML='<section class="holding ibet-audience"><p>I BET YOU</p><h1>ROUND COMPLETE</h1></section>';return}let content='';if(model.phase==='waiting')content=`<p class="kicker">I BET YOU</p><h1>GROUP ${model.groupNumber}</h1><div class="ibet-audience-teams">${model.members.map(m=>`<strong>${mascotEmoji(m.mascot_id)} ${esc(m.name)}</strong>`).join('')}</div><p class="ibet-category-label">CATEGORY</p><h2>${esc(model.category)}</h2>`;if(model.phase==='bidding')content=`<p class="kicker">${identity(group.current_bidder_team_id)}</p><h1>I BET YOU CAN NAME…</h1><div class="ibet-audience-bid">${model.bid}</div><h2>${esc(model.category)}</h2>`;if(model.phase==='challenged')content=`<p class="kicker">${identity(group.challenger_team_id)} SAYS</p><h1>NAME THEM!</h1><p class="ibet-must-name">${identity(group.challenged_bidder_team_id)} MUST NAME</p><div class="ibet-audience-bid">${model.bid}</div><h2>${esc(model.category)}</h2>`;if(model.phase==='countdown')content=`<p class="kicker">${identity(group.challenged_bidder_team_id)} · NAME ${model.bid}</p><div class="ibet-audience-timer">${model.seconds}</div><h2>${model.seconds?'SECONDS':'TIME’S UP'}</h2><p>${esc(model.category)}</p>`;if(model.phase==='result'||model.phase==='complete')content=`<p class="kicker">${model.result==='success'?'SUCCESS':'FAILED'}</p><h1>${identity(group.winning_team_id)}</h1><div class="ibet-points">+5</div><h2>${model.result==='success'?'TAKES THE POINTS':'STEALS THE POINTS'}</h2>`;root.innerHTML=`<section class="holding ibet-audience">${content}</section>`;if(model.phase==='countdown')ticker=setInterval(()=>renderIBetYou(),250)}
async function hydrate(){const next=await hydrateAudience(supabase,room);if(containsSecretData(next))throw new Error('Unsafe audience payload');state=next;render();return next}
async function subscribe(){if(channel)await supabase.removeChannel(channel);channel=supabase.channel(`event:${state.event.id}:public`,{config:{private:true}}).on('broadcast',{event:'state_changed'},hydrate).subscribe(status=>{if(status==='SUBSCRIBED')hydrate()})}
async function init(){if(getSupabaseConfigError()){root.innerHTML='<section class="holding"><h1>Configuration required</h1></section>';return}try{await ensureAnonymousSession(supabase);await hydrate();if(!state)throw new Error('Room unavailable');await subscribe()}catch(err){console.error(err);root.innerHTML='<section class="holding"><p>ROOM UNAVAILABLE</p><h1>Game Night</h1></section>'}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state)hydrate()});supabase?.auth.onAuthStateChange(event=>{if(event==='TOKEN_REFRESHED'&&state)hydrate()})
if(!room)import('../audience.js');else if(!ROOM_PATTERN.test(room))root.innerHTML='<section class="holding"><h1>Invalid room</h1></section>';else init()
