import { createGameNightClient, getSupabaseConfigError } from './supabase-client.js'
import { ensureAnonymousSession, normalizeRoom, ROOM_PATTERN } from './team-service.js'
import { containsSecretData, hydrateAudience, secondsRemaining } from './audience-service.js'
import QRCode from 'qrcode'
import { animateCountUp,buildCountUpTrack,differencePresentation,lockCountChange,resultPointsLabel,revealFrame,revealLayout,suspenseSeconds,teamJoinUrl } from './audience-view.js'
import { iBetYouAudienceModel } from './i-bet-you.js'
import { mascotEmoji } from './mascots.js'

const root=document.getElementById('audienceApp'),room=normalizeRoom(new URLSearchParams(location.search).get('room')??''),supabase=createGameNightClient('game-night-audience-auth')
let state=null,channel=null,ticker=null,lastAnimatedQuestion=null,revealShouldAnimate=false,revealAnimating=false,lastAnswerCount=null,lockCountPop=false
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))
function image(q){const url=q?.external_image_url||(q?.image_kind==='storage'?`${import.meta.env.VITE_SUPABASE_URL}/storage/v1/object/public/celebrity-images/${q.image_path}`:'');return url?`<div class="portrait-bg" style="background-image:url('${esc(url)}')"></div><img class="portrait-main" src="${esc(url)}" alt="${esc(q.celebrity_name)}">`:`<span>${esc((q?.celebrity_name||'?').split(' ').map(x=>x[0]).slice(0,2).join(''))}</span>`}
function imageUrl(q){return q?.external_image_url||(q?.image_kind==='storage'?`${import.meta.env.VITE_SUPABASE_URL}/storage/v1/object/public/celebrity-images/${q.image_path}`:'')}
function revealStage(q,settled=false){const track=buildCountUpTrack(state.guess_markers||[],q.correct_age),layout=revealLayout(track.markers.length),photo=imageUrl(q),frame=settled?revealFrame(track.max,track):revealFrame(1,track);return {track,html:`<section class="screen count-reveal${layout.dense?' dense':''}${settled?' answer-landed overshooting final':''}" id="ageRevealStage" style="--result-columns:${layout.columns};--primary-progress:${frame.primaryProgress}%;--overshoot-progress:${frame.overshootProgress}%;--answer-position:${track.answerPosition}%">${photo?`<div class="reveal-celebrity-bg" style="background-image:url('${esc(photo)}')"></div>`:''}<header><span>GUESS THE AGE</span><span>${track.markers.length} TEAM RESULTS</span></header><div class="count-reveal-title"><p>${esc(q.celebrity_name)} IS…</p><strong id="revealCounter">${settled?q.correct_age:1}</strong><small id="counterLabel">${settled?'CORRECT AGE':'COUNTING UP'}</small></div><div class="count-track"><div class="track-base"></div><div class="track-primary"></div><div class="track-overshoot"></div><div class="answer-stop"><i>★</i><b>${q.correct_age}</b></div>${track.markers.map(marker=>{const difference=differencePresentation(marker.signed_difference),visible=settled?' revealed':'';return `<article class="count-marker${visible}" data-guess="${marker.guess}" style="--position:${marker.position}%;--lane:${marker.lane}"><div class="marker-stem"></div><div class="marker-pill">${mascotEmoji(marker.mascot_id)} <b>${marker.guess}</b></div><div class="marker-result"><strong>${esc(marker.team_name)}</strong><span>${difference.long}</span><b class="${marker.points?'positive':'zero'}">${resultPointsLabel(marker.points)}</b></div></article>`}).join('')}</div></section>`}}
function applyRevealFrame(frame){const stage=document.getElementById('ageRevealStage');if(!stage)return;stage.style.setProperty('--primary-progress',`${frame.primaryProgress}%`);stage.style.setProperty('--overshoot-progress',`${frame.overshootProgress}%`);document.getElementById('revealCounter').textContent=frame.age;stage.classList.toggle('overshooting',frame.overshooting);if(frame.overshooting)document.getElementById('counterLabel').textContent='HIGH GUESSES';stage.querySelectorAll('.count-marker').forEach(marker=>{if(Number(marker.dataset.guess)<=frame.age)marker.classList.add('revealed')})}
async function renderJoin(){const url=teamJoinUrl(location.origin,state.event.room_code);root.innerHTML=`<section class="holding join-screen"><div class="orb"></div><p>${esc(state.event.venue)}</p><h1>${esc(state.event.name)}</h1><h2>Join Game Night</h2><img id="joinQr" class="join-qr" alt="Scan to join room ${esc(state.event.room_code)}"><div class="join"><span>ROOM CODE</span><strong>${esc(state.event.room_code)}</strong></div><small>SCAN TO JOIN YOUR TEAM</small><div class="join-url">${esc(url)}</div></section>`;document.getElementById('joinQr').src=await QRCode.toDataURL(url,{width:420,margin:2,errorCorrectionLevel:'M',color:{dark:'#08090d',light:'#ffffff'}})}
function render(){clearInterval(ticker);if(!state)return;const e=state.event,q=state.question,r=state.round,left=secondsRemaining(state),expired=e.status==='question'&&left<=0;
  if(e.display_mode==='join'){renderJoin().catch(console.error);return}
  if(e.display_mode==='leaderboard'){root.innerHTML=`<section class="screen leaderboard"><header><span>${esc(e.venue)}</span><span>${esc(e.name)}</span></header><div class="board-wrap"><p class="kicker">CURRENT STANDINGS</p><h1>Leaderboard</h1><div class="board">${(state.leaderboard||[]).map((t,i)=>`<div class="board-row ${i<3?'top':''}"><span class="place">${i+1}</span><strong>${mascotEmoji(t.mascot_id)} ${esc(t.name)}</strong><span class="points">${t.points}<small> pts</small></span></div>`).join('')}</div></div></section>`;return}
  if(state.i_bet_you?.round?.id===e.active_round_id){renderIBetYou();return}
  if(!q||['lobby','ready','round_complete'].includes(e.status)){root.innerHTML=`<section class="holding"><div class="orb"></div><p>${esc(e.venue)}</p><h1>${esc(e.name)}</h1><small>${e.status==='round_complete'?'ROUND COMPLETE':'GET READY'}</small></section>`;return}
  if(e.status==='suspense'){const suspense=suspenseSeconds(state);root.innerHTML=`<section class="holding suspense"><p>ANSWERS LOCKED</p><h1>Reveal in <span id="suspenseCount">${suspense}</span></h1><div class="locked-total">${state.submitted_count} / ${state.team_count}<small>TEAMS LOCKED IN</small></div></section>`;ticker=setInterval(()=>{const n=suspenseSeconds(state);const el=document.getElementById('suspenseCount');if(el)el.textContent=n;if(n<=0)hydrate().catch(console.error)},250);return}
  const reveal=e.status==='reveal',locked=e.status==='locked'||expired;if(reveal){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,animate=revealShouldAnimate&&lastAnimatedQuestion!==q.id&&!reduced,built=revealStage(q,!animate);root.innerHTML=built.html;if(!animate){lastAnimatedQuestion=q.id;revealAnimating=false;return}lastAnimatedQuestion=q.id;revealAnimating=true;revealShouldAnimate=false;animateCountUp({track:built.track,onFrame:applyRevealFrame,onCorrect:()=>{const stage=document.getElementById('ageRevealStage');stage?.classList.add('answer-landed');const label=document.getElementById('counterLabel');if(label)label.textContent='CORRECT AGE'},onComplete:()=>{const stage=document.getElementById('ageRevealStage');stage?.classList.add('final');document.getElementById('revealCounter').textContent=q.correct_age;document.getElementById('counterLabel').textContent='CORRECT AGE';revealAnimating=false}}).catch(err=>{console.error(err);revealAnimating=false;render()});return}root.innerHTML=`<section class="screen question-screen ${locked?'locked':'question'}"><header><span>ROUND ${r?.position||1} · ${esc(r?.title||'Guess the Age')}</span><span>QUESTION ${q.position} / ${r?.question_count||0}</span></header><div class="question-layout"><div class="portrait">${image(q)}</div><div class="copy"><p class="kicker">HOW OLD IS</p><h1>${esc(q.celebrity_name)}?</h1><div class="answer-count prominent${lockCountPop?' count-pop':''}"><strong>${state.submitted_count} / ${state.team_count}</strong><span>TEAMS LOCKED IN</span></div></div><div class="countdown ${locked?'locked':''}">${e.status==='question'&&!expired?`<strong>${left}</strong><span>SECONDS</span>`:'<strong>✓</strong><span>ANSWERS LOCKED</span>'}</div></div></section>`;
  if(e.status==='question'&&!expired)ticker=setInterval(()=>{const remaining=secondsRemaining(state);if(remaining<=0)render();else{const el=document.querySelector('.countdown strong');if(el)el.textContent=remaining}},250)
}
function renderIBetYou(){const model=iBetYouAudienceModel(state),game=state.i_bet_you,group=game.groups.find(g=>g.id===game.round.active_group_id),identity=id=>{const member=group?.members.find(x=>x.team_id===id);return `${mascotEmoji(member?.mascot_id)} ${esc(member?.name||'Team')}`};if(model.phase==='complete'||!group){root.innerHTML='<section class="holding ibet-audience"><p>I BET YOU</p><h1>ROUND COMPLETE</h1></section>';return}let content='';if(model.phase==='waiting')content=`<p class="kicker">I BET YOU</p><h1>GROUP ${model.groupNumber}</h1><div class="ibet-audience-teams">${model.members.map(m=>`<strong>${mascotEmoji(m.mascot_id)} ${esc(m.name)}</strong>`).join('')}</div><p class="ibet-category-label">CATEGORY</p><h2>${esc(model.category)}</h2>`;if(model.phase==='bidding')content=`<p class="kicker">${identity(group.current_bidder_team_id)}</p><h1>I BET YOU CAN NAME…</h1><div class="ibet-audience-bid">${model.bid}</div><h2>${esc(model.category)}</h2>`;if(model.phase==='challenged')content=`<p class="kicker">${identity(group.challenger_team_id)} SAYS</p><h1>NAME THEM!</h1><p class="ibet-must-name">${identity(group.challenged_bidder_team_id)} MUST NAME</p><div class="ibet-audience-bid">${model.bid}</div><h2>${esc(model.category)}</h2>`;if(model.phase==='countdown')content=`<p class="kicker">${identity(group.challenged_bidder_team_id)} · NAME ${model.bid}</p><div class="ibet-audience-timer">${model.seconds}</div><h2>${model.seconds?'SECONDS':'TIME’S UP'}</h2><p>${esc(model.category)}</p>`;if(model.phase==='result'||model.phase==='complete')content=`<p class="kicker">${model.result==='success'?'SUCCESS':'FAILED'}</p><h1>${identity(group.winning_team_id)}</h1><div class="ibet-points">+5</div><h2>${model.result==='success'?'TAKES THE POINTS':'STEALS THE POINTS'}</h2>`;root.innerHTML=`<section class="holding ibet-audience">${content}</section>`;if(model.phase==='countdown')ticker=setInterval(()=>renderIBetYou(),250)}
async function hydrate(){const next=await hydrateAudience(supabase,room);if(containsSecretData(next))throw new Error('Unsafe audience payload');const previousStatus=state?.event?.status,transitioned=Boolean(state)&&previousStatus!=='reveal'&&next?.event?.status==='reveal',change=lockCountChange(lastAnswerCount,next?.submitted_count,matchMedia('(prefers-reduced-motion: reduce)').matches);lastAnswerCount=next?.submitted_count;lockCountPop=change.pop;state=next;if(transitioned)revealShouldAnimate=true;if(revealAnimating&&next?.event?.status==='reveal')return next;render();return next}
async function subscribe(){if(channel)await supabase.removeChannel(channel);channel=supabase.channel(`event:${state.event.id}:public`,{config:{private:true}}).on('broadcast',{event:'state_changed'},hydrate).subscribe(status=>{if(status==='SUBSCRIBED')hydrate()})}
async function init(){if(getSupabaseConfigError()){root.innerHTML='<section class="holding"><h1>Configuration required</h1></section>';return}try{await ensureAnonymousSession(supabase);await hydrate();if(!state)throw new Error('Room unavailable');await subscribe()}catch(err){console.error(err);root.innerHTML='<section class="holding"><p>ROOM UNAVAILABLE</p><h1>Game Night</h1></section>'}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state)hydrate()});supabase?.auth.onAuthStateChange(event=>{if(event==='TOKEN_REFRESHED'&&state)hydrate()})
if(!room)import('../audience.js');else if(!ROOM_PATTERN.test(room))root.innerHTML='<section class="holding"><h1>Invalid room</h1></section>';else init()
