import { createGameNightClient, getSupabaseConfigError } from './supabase-client.js'
import { ensureAnonymousSession, normalizeRoom, ROOM_PATTERN } from './team-service.js'
import { containsSecretData, hydrateAudience, secondsRemaining } from './audience-service.js'

const root=document.getElementById('audienceApp'),room=normalizeRoom(new URLSearchParams(location.search).get('room')??''),supabase=createGameNightClient('game-night-audience-auth')
let state=null,channel=null,ticker=null
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))
function image(q){const url=q?.external_image_url||(q?.image_kind==='storage'?`${import.meta.env.VITE_SUPABASE_URL}/storage/v1/object/public/celebrity-images/${q.image_path}`:'');return url?`<div class="portrait-bg" style="background-image:url('${esc(url)}')"></div><img class="portrait-main" src="${esc(url)}" alt="${esc(q.celebrity_name)}">`:`<span>${esc((q?.celebrity_name||'?').split(' ').map(x=>x[0]).slice(0,2).join(''))}</span>`}
function render(){clearInterval(ticker);if(!state)return;const e=state.event,q=state.question,r=state.round,left=secondsRemaining(state),expired=e.status==='question'&&left<=0;
  if(e.status==='leaderboard'){root.innerHTML=`<section class="screen leaderboard"><header><span>${esc(e.venue)}</span><span>${esc(e.name)}</span></header><div class="board-wrap"><p class="kicker">CURRENT STANDINGS</p><h1>Leaderboard</h1><div class="board">${(state.leaderboard||[]).map((t,i)=>`<div class="board-row ${i<3?'top':''}"><span class="place">${i+1}</span><strong>${esc(t.name)}</strong><span class="points">${t.points}<small> pts</small></span></div>`).join('')}</div></div></section>`;return}
  if(!q||['lobby','ready','round_complete'].includes(e.status)){root.innerHTML=`<section class="holding"><div class="orb"></div><p>${esc(e.venue)}</p><h1>${esc(e.name)}</h1><div class="join"><span>ROOM</span><strong>${esc(e.room_code)}</strong></div><small>${e.status==='round_complete'?'ROUND COMPLETE':'GET READY'}</small></section>`;return}
  const reveal=e.status==='reveal',locked=e.status==='locked'||expired;root.innerHTML=`<section class="screen question-screen ${reveal?'reveal':locked?'locked':'question'}"><header><span>ROUND ${r?.position||1} · ${esc(r?.title||'Guess the Age')}</span><span>QUESTION ${q.position} / ${r?.question_count||0}</span></header><div class="question-layout"><div class="portrait">${image(q)}</div><div class="copy"><p class="kicker">GUESS THE AGE</p><h1>${esc(q.celebrity_name)}</h1>${reveal?`<div class="answer"><span>ACTUAL AGE</span><strong>${q.correct_age}</strong></div>`:'<p class="prompt">How old are they?</p>'}<div class="answer-count">${state.answer_count} / ${state.team_count} Teams locked in</div></div><div class="countdown ${locked?'locked':''}">${e.status==='question'&&!expired?`<strong>${left}</strong><span>SECONDS</span>`:locked?'<strong>✓</strong><span>ANSWERS LOCKED</span>':'<strong>!</strong><span>REVEAL</span>'}</div></div></section>`;
  if(e.status==='question'&&!expired)ticker=setInterval(()=>{const remaining=secondsRemaining(state);if(remaining<=0)render();else{const el=document.querySelector('.countdown strong');if(el)el.textContent=remaining}},250)
}
async function hydrate(){const next=await hydrateAudience(supabase,room);if(containsSecretData(next))throw new Error('Unsafe audience payload');state=next;render();return next}
async function subscribe(){if(channel)await supabase.removeChannel(channel);channel=supabase.channel(`event:${state.event.id}:public`,{config:{private:true}}).on('broadcast',{event:'state_changed'},hydrate).subscribe(status=>{if(status==='SUBSCRIBED')hydrate()})}
async function init(){if(getSupabaseConfigError()){root.innerHTML='<section class="holding"><h1>Configuration required</h1></section>';return}try{await ensureAnonymousSession(supabase);await hydrate();if(!state)throw new Error('Room unavailable');await subscribe()}catch(err){console.error(err);root.innerHTML='<section class="holding"><p>ROOM UNAVAILABLE</p><h1>Game Night</h1></section>'}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state)hydrate()});supabase?.auth.onAuthStateChange(event=>{if(event==='TOKEN_REFRESHED'&&state)hydrate()})
if(!room)import('../audience.js');else if(!ROOM_PATTERN.test(room))root.innerHTML='<section class="holding"><h1>Invalid room</h1></section>';else init()
