export const DEFAULT_PERFECT_LIE_CATEGORIES=['This Week','Sport','Entertainment','General Knowledge']
export function createPerfectLieQuestion(){return {question_text:'',correct_answer:'',accepted_answer_variants:[],explanation:'',source_reference:''}}
export function createPerfectLieCategory(title='New Category',questionCount=0){return {title,questions:Array.from({length:questionCount},createPerfectLieQuestion)}}
export function createPerfectLieDraft(){return {title:'Perfect Lie',categories:DEFAULT_PERFECT_LIE_CATEGORIES.map(title=>createPerfectLieCategory(title,3))}}
export function movePerfectLieItem(items,index,delta){const target=index+delta;if(index<0||target<0||target>=items.length)return items;[items[index],items[target]]=[items[target],items[index]];return items}
export function perfectLieValidationError(categories=[]){if(!categories.length)return'Add at least one category.';for(const [ci,category]of categories.entries()){if(!category.title?.trim())return`Category ${ci+1} needs a name.`;if(!category.questions?.length)return`${category.title.trim()} needs at least one question.`;for(const [qi,question]of category.questions.entries()){if(!question.question_text?.trim())return`${category.title.trim()}, question ${qi+1} needs question text.`;if(!question.correct_answer?.trim())return`${category.title.trim()}, question ${qi+1} needs a correct answer.`}}return null}
export function perfectLiePayload(categories=[]){return categories.map(category=>({title:category.title.trim(),questions:category.questions.map(question=>({question_text:question.question_text.trim(),correct_answer:question.correct_answer.trim(),accepted_answer_variants:Array.isArray(question.accepted_answer_variants)?question.accepted_answer_variants.map(x=>x.trim()).filter(Boolean):String(question.accepted_answer_variants||'').split(',').map(x=>x.trim()).filter(Boolean),explanation:question.explanation?.trim()||'',source_reference:question.source_reference?.trim()||''}))}))}
export function friendlyPerfectLieError(error){const message=String(error?.message||'');if(message.includes('Someone else beat'))return'Someone else beat you to that one. Try another lie.';if(message.includes('real answer'))return'That’s the real answer — you need a lie.';if(message.includes('own lie'))return'You cannot vote for your own lie.';if(message.includes('answer window is closed'))return'The truth window ended. You can still submit a lie.';if(message.includes('submissions are closed'))return'Submissions have closed. Watch the main screen.';return'Could not save that response. Please try again.'}
export function perfectLieTeamState(game,{knowledgeExpired=false}={}){if(!game?.round?.phase)return{view:'reconnecting'};const phase=game.round.phase;if(phase==='writing'){if(game.my_lie)return{view:'lie_waiting'};if(game.my_response?.timed_out)return{view:'lie_timeout'};if(game.my_response?.knew_truth)return{view:'lie_correct'};if(game.my_response)return{view:'lie_wrong',draft:game.my_response.initial_answer||''};if(knowledgeExpired)return{view:'lie_timeout',needsTimeoutTransition:true};return{view:'initial_answer'}}if(phase==='voting')return{view:game.my_vote?'vote_waiting':'vote'};if(phase==='reveal'||phase==='question_complete')return{view:'result'};if(phase==='complete')return{view:'complete'};if(['setup','ready','category_transition'].includes(phase))return{view:'waiting'};return{view:'reconnecting'}}
