export const TABLE_OF_LIES_NAME='Table of Lies'
export const TABLE_OF_LIES_LABEL='TABLE OF LIES'
export const perfectLieDisplayTitle=title=>String(title||'').replaceAll('Perfect Lie',TABLE_OF_LIES_NAME)
export const DEFAULT_PERFECT_LIE_CATEGORIES=['This Week','Sport','Entertainment','General Knowledge']
export function createPerfectLieQuestion(){return {question_text:'',correct_answer:'',accepted_answer_variants:[],explanation:'',source_reference:''}}
export function createPerfectLieCategory(title='New Category',questionCount=0){return {title,questions:Array.from({length:questionCount},createPerfectLieQuestion)}}
export function createPerfectLieDraft(){return {title:TABLE_OF_LIES_NAME,categories:DEFAULT_PERFECT_LIE_CATEGORIES.map(title=>createPerfectLieCategory(title,3))}}
export function movePerfectLieItem(items,index,delta){const target=index+delta;if(index<0||target<0||target>=items.length)return items;[items[index],items[target]]=[items[target],items[index]];return items}
export function perfectLieValidationError(categories=[]){if(!categories.length)return'Add at least one category.';for(const [ci,category]of categories.entries()){if(!category.title?.trim())return`Category ${ci+1} needs a name.`;if(!category.questions?.length)return`${category.title.trim()} needs at least one question.`;for(const [qi,question]of category.questions.entries()){if(!question.question_text?.trim())return`${category.title.trim()}, question ${qi+1} needs question text.`;if(!question.correct_answer?.trim())return`${category.title.trim()}, question ${qi+1} needs a correct answer.`}}return null}
export function perfectLiePayload(categories=[]){return categories.map(category=>({title:category.title.trim(),questions:category.questions.map(question=>({question_text:question.question_text.trim(),correct_answer:question.correct_answer.trim(),accepted_answer_variants:Array.isArray(question.accepted_answer_variants)?question.accepted_answer_variants.map(x=>x.trim()).filter(Boolean):String(question.accepted_answer_variants||'').split(',').map(x=>x.trim()).filter(Boolean),explanation:question.explanation?.trim()||'',source_reference:question.source_reference?.trim()||''}))}))}
export function friendlyPerfectLieError(error){const message=String(error?.message||''),normalized=message.toLowerCase();if(normalized.includes('already been submitted'))return'Your answer is already locked in.';if(normalized.includes('already finalized')||normalized.includes('already submitted a final lie')||(error?.code==='55000'&&message.includes('Someone else beat')))return'Your Team has already locked in its lie.';if(message.includes('Someone else beat'))return'Someone else has already used that lie. Try another one.';if(normalized.includes('real answer'))return'That’s the real answer — write something the other tables will believe.';if(normalized.includes('own lie'))return'You can’t vote for your own answer.';if(normalized.includes('already voted'))return'Your Team’s vote is already locked in.';if(normalized.includes('answer window is closed'))return'Time’s up for the first answer. You can still submit a lie.';if(normalized.includes('submissions have closed'))return'Lie writing has ended. Watch the main screen.';if(normalized.includes('voting is closed'))return'Voting has ended. Watch the main screen.';return'We couldn’t update the game. Check your connection and try again.'}
export function perfectLieTeamState(game,{knowledgeExpired=false}={}){if(!game?.round?.phase)return{view:'reconnecting'};const phase=game.round.phase;if(phase==='writing'){if(game.my_lie)return{view:'lie_waiting'};if(game.my_response?.timed_out)return{view:'lie_timeout'};if(game.my_response?.knew_truth)return{view:'lie_correct'};if(game.my_response)return{view:'lie_wrong',draft:game.my_response.initial_answer||''};if(knowledgeExpired)return{view:'lie_timeout'};return{view:'initial_answer'}}if(phase==='voting')return{view:game.my_vote?'vote_waiting':'vote'};if(phase==='reveal'||phase==='question_complete')return{view:'result'};if(phase==='complete')return{view:'complete'};if(['setup','ready','category_transition'].includes(phase))return{view:'waiting'};return{view:'reconnecting'}}
export const canPreparePerfectLieQuestion=phase=>['ready','category_transition'].includes(phase)
export function perfectLieMissingConfirmation(kind,complete,total){const missing=Math.max(0,Number(total||0)-Number(complete||0));if(!missing)return'';if(kind==='lies')return`${missing} Team${missing===1?'':'s'} still ${missing===1?'hasn’t':'haven’t'} submitted a lie. Close submissions anyway?`;return`${missing} Team${missing===1?'':'s'} still ${missing===1?'hasn’t':'haven’t'} voted. Start the reveal anyway?`}
export const perfectLieRevealProgress=(index,total,complete=false)=>`REVEAL ${Number(index||0)} OF ${Number(total||0)}${complete?' · COMPLETE':''}`
export function mergePerfectLieEditorSnapshot(local,remote,{dirty=false}={}){if(dirty)return{draft:local,remoteChanged:true};return{draft:structuredClone(remote),remoteChanged:false}}
