import{describe,expect,it}from'vitest'
import{canPreparePerfectLieQuestion,createPerfectLieDraft,friendlyPerfectLieError,mergePerfectLieEditorSnapshot,movePerfectLieItem,perfectLieMissingConfirmation,perfectLiePayload,perfectLieRevealProgress,perfectLieTeamState,perfectLieValidationError,TABLE_OF_LIES_LABEL,TABLE_OF_LIES_NAME}from'./perfect-lie.js'

describe('Table of Lies setup',()=>{
  it('centralizes the player-facing name while retaining internal module identity',()=>{expect(TABLE_OF_LIES_NAME).toBe('Table of Lies');expect(TABLE_OF_LIES_LABEL).toBe('TABLE OF LIES');expect(createPerfectLieDraft().title).toBe(TABLE_OF_LIES_NAME)})
  it('creates four editable categories with three empty questions each',()=>{const draft=createPerfectLieDraft();expect(draft.categories.map(x=>x.title)).toEqual(['This Week','Sport','Entertainment','General Knowledge']);expect(draft.categories.every(x=>x.questions.length===3)).toBe(true)})
  it('supports arbitrary add/remove/reordering',()=>{const draft=createPerfectLieDraft();draft.categories.push({title:'Ireland',questions:[]});movePerfectLieItem(draft.categories,4,-1);expect(draft.categories[3].title).toBe('Ireland');draft.categories.splice(0,1);expect(draft.categories).toHaveLength(4)})
  it('validates missing content with its location',()=>{const draft=createPerfectLieDraft();expect(perfectLieValidationError(draft.categories)).toContain('This Week, question 1');draft.categories[0].questions[0].question_text='Question?';expect(perfectLieValidationError(draft.categories)).toContain('correct answer')})
  it('normalizes variants into the RPC payload',()=>{const payload=perfectLiePayload([{title:' Sport ',questions:[{question_text:' Q? ',correct_answer:' A ',accepted_answer_variants:'A1, A2',explanation:' E ',source_reference:' S '}]}]);expect(payload[0].questions[0]).toMatchObject({question_text:'Q?',correct_answer:'A',accepted_answer_variants:['A1','A2']})})
  it('maps specific player-safe errors',()=>{expect(friendlyPerfectLieError({message:'Someone else beat you',code:'23505'})).toContain('already used');expect(friendlyPerfectLieError({message:'Someone else beat you',code:'55000'})).toContain('already locked');expect(friendlyPerfectLieError({message:'An answer has already been submitted'})).toContain('already locked');expect(friendlyPerfectLieError({message:'already finalized'})).toContain('already locked');expect(friendlyPerfectLieError({message:'already voted'})).toContain('already locked');expect(friendlyPerfectLieError({message:'network'})).toContain('connection')})
  it('uses player-friendly timeout language without backend terminology',()=>{const message=friendlyPerfectLieError({message:'The answer window is closed.'});expect(message).toBe('Time’s up for the first answer. You can still submit a lie.');expect(message.toLowerCase()).not.toContain('truth window')})
  it('maps atomic late-lie closure without exposing the database error',()=>expect(friendlyPerfectLieError({message:'Lie submissions have closed.'})).toBe('Lie writing has ended. Watch the main screen.'))
  it('locks prepared-question mutation throughout live play',()=>{expect(canPreparePerfectLieQuestion('ready')).toBe(true);expect(canPreparePerfectLieQuestion('category_transition')).toBe(true);for(const phase of['writing','voting','reveal','question_complete'])expect(canPreparePerfectLieQuestion(phase)).toBe(false)})
  it('warns before incomplete closure or reveal',()=>{expect(perfectLieMissingConfirmation('lies',8,10)).toContain('2 Teams');expect(perfectLieMissingConfirmation('votes',7,10)).toContain('3 Teams');expect(perfectLieMissingConfirmation('lies',10,10)).toBe('')})
  it('shows useful reveal progress without future content',()=>{expect(perfectLieRevealProgress(2,5)).toBe('REVEAL 2 OF 5');expect(perfectLieRevealProgress(5,5,true)).toContain('COMPLETE')})
  it('preserves a dirty editor when a remote Team broadcast arrives',()=>{const local=[{title:'Unsaved'}],remote=[{title:'Server'}];expect(mergePerfectLieEditorSnapshot(local,remote,{dirty:true})).toEqual({draft:local,remoteChanged:true});const clean=mergePerfectLieEditorSnapshot(local,remote);expect(clean.remoteChanged).toBe(false);expect(clean.draft).toEqual(remote);expect(clean.draft).not.toBe(remote)})
})

describe('Table of Lies Team state mapping',()=>{
  const game=(phase,extra={})=>({round:{phase},...extra})
  it('maps every writing substate independently',()=>{expect(perfectLieTeamState(game('writing')).view).toBe('initial_answer');expect(perfectLieTeamState(game('writing',{my_response:{knew_truth:true}})).view).toBe('lie_correct');expect(perfectLieTeamState(game('writing',{my_response:{knew_truth:false,initial_answer:'Elvis'}}))).toEqual({view:'lie_wrong',draft:'Elvis'});expect(perfectLieTeamState(game('writing',{my_lie:{text:'Pirates'}})).view).toBe('lie_waiting')})
  it('gives an authoritative final lie precedence over every initial response type',()=>{for(const my_response of[{knew_truth:false,initial_answer:'Wrong'},{knew_truth:true,initial_answer:'Truth'},{timed_out:true,initial_answer:null}])expect(perfectLieTeamState(game('writing',{my_response,my_lie:{id:'lie-1',text:'Final lie'}})).view).toBe('lie_waiting')})
  it('keeps the wrong answer as the editable lie draft until persisted',()=>expect(perfectLieTeamState(game('writing',{my_response:{knew_truth:false,initial_answer:'Original wrong answer'},my_lie:null}))).toEqual({view:'lie_wrong',draft:'Original wrong answer'}))
  it('uses one atomic timeout route with no transition flag',()=>expect(perfectLieTeamState(game('writing'),{knowledgeExpired:true})).toEqual({view:'lie_timeout'}))
  it('restores a persisted timeout response to lie writing',()=>expect(perfectLieTeamState(game('writing',{my_response:{timed_out:true}})).view).toBe('lie_timeout'))
  it('maps voting before and after a vote',()=>{expect(perfectLieTeamState(game('voting',{options:[]})).view).toBe('vote');expect(perfectLieTeamState(game('voting',{my_vote:'option'})).view).toBe('vote_waiting')})
  it('maps reveal to result without controls',()=>expect(perfectLieTeamState(game('reveal')).view).toBe('result'))
  it('uses reconnecting for missing or unknown state',()=>{expect(perfectLieTeamState(null).view).toBe('reconnecting');expect(perfectLieTeamState(game('mystery')).view).toBe('reconnecting')})
})
